import type { AppState, Scenario, User, Group, Location, AlarmPlan, AlarmButton, EmergencyContact, IntegrationSettings } from './types'

// Vorkonfigurierte Notfallszenarien für das heilpädagogische Kompetenzzentrum SONNENBERG
/** Inhaltsversion der Standard-Szenarien – bei Erhöhung werden sie beim Laden aktualisiert */
export const SCENARIO_CONTENT_VERSION = 8

export const SEED_SCENARIOS: Scenario[] = [
  {
    id: 'sc-brand', icon: 'flame', title: 'Brand / Feuer', category: 'Gebäude & Technik', priority: 'hoch', silentDefault: false,
    defaultChannels: ['push', 'sms', 'tts'], responsibleGroupIds: ['gr-alle'], contactIds: ['ec-118', 'ec-144'],
    callGuidance: [
      'Feuerwehr 118 anrufen – bei jedem Brand, auch bei einem kleinen und selbst gelöschten.',
      'In dieser Reihenfolge melden: Wer meldet (Name, Rückrufnummer), wo (Standort, Gebäude, Stockwerk, Raum), was brennt, wie viele Personen betroffen sind, ob Menschen in Gefahr sind.',
      'Ausdrücklich sagen: Sonderschule mit Kindern, die das Gebäude nicht selbständig verlassen können.',
      'Bei Verletzten oder Rauchgaseinwirkung zusätzlich Sanitätsnotruf 144.',
      'Leitung offen halten, bis die Notrufzentrale das Gespräch beendet – nicht selbst auflegen.',
    ],
    instructions: [
      'Eigenschutz zuerst: Nur handeln, solange Sie sich selbst nicht gefährden. Rauch ist gefährlicher als Feuer.',
      'Personen aus dem unmittelbaren Gefahrenbereich bringen – Türe zum Brandraum schliessen, nicht abschliessen.',
      'Nur einen Entstehungsbrand mit dem Handfeuerlöscher bekämpfen. Bei Rauchentwicklung im Raum: sofort raus.',
      'Klasse geschlossen über den nächsten freien Fluchtweg zum Sammelplatz führen – Klassenliste mitnehmen, keine Aufzüge benutzen.',
      'Schüler:innen mit Mobilitätseinschränkung nach dem persönlichen Evakuationsplan begleiten; im Notfall in einen sicheren Bereich hinter einer Brandschutztüre bringen und den Standort sofort der Feuerwehr melden.',
      'Feuerwehr an der vereinbarten Zufahrt einweisen und über vermisste Personen informieren.',
    ],
    responseSteps: [
      { text: 'Kein zweiter Notruf: Die Feuerwehr ist alarmiert. Anrufen nur, wenn Sie Neues wissen – Personen in Gefahr, Feuer breitet sich aus.' },
      { text: 'Am betroffenen Standort: Unterricht sofort beenden, Klasse sammeln, Klassenliste mitnehmen, über den nächsten freien Fluchtweg zum Sammelplatz.' },
      { text: 'Schüler:innen mit persönlichem Evakuationsplan nach Plan begleiten – festgelegte Begleitperson, Tragehilfe, Evakuationsstuhl.' },
      { text: 'Raum kontrollieren, auch WC und Nebenräume; Türe schliessen, nicht abschliessen.' },
      { text: 'Evakuationshelfer: zugeteilte Etage abgehen, Räume kontrollieren, Personen mit Evakuationsplan zum Sammelplatz begleiten, danach der Evakuationsleitung Vollzug melden.', groupIds: ['gr-evak'] },
      { text: 'Am Sammelplatz zählen und der Evakuationsleitung melden – auch wenn alle da sind.' },
      { text: 'Ersthelfer: mit Notfallrucksack zum Sammelplatz; Verletzte und Rauchgaseinwirkung versorgen, Rettungsdienst nachfordern.', groupIds: ['gr-ersthelfer'] },
      { text: 'Hausdienst: Feuerwehr an der Zufahrt einweisen, Schlüssel und Gebäudepläne bereithalten, Aufzüge ausser Betrieb.', groupIds: ['gr-sicherheit'] },
      { text: 'An einem anderen Standort: nichts unternehmen, erreichbar bleiben, den betroffenen Standort nicht anrufen – die Leitungen werden gebraucht.' },
      { text: 'Nicht ins Gebäude zurück, bis die Feuerwehr freigibt. Weisungen der Einsatzleitung gehen allen anderen vor.' },
    ],
    allClearSteps: [
      'Rückkehr ins Gebäude nur über die freigegebenen Wege – Anweisungen der Feuerwehr und der Evakuationsleitung befolgen.',
      'Klasse im Raum erneut zählen und die Vollständigkeit der Evakuationsleitung melden.',
      'Kinder beruhigen und den Tagesablauf möglichst normal weiterführen; auffällige Reaktionen der Klassenleitung melden.',
      'Verletzungen oder Rauchgaseinwirkung, auch leichte, der Schulleitung melden – Unfallmeldung.',
      'Beobachtungen (Zeiten, Ablauf, Probleme) noch heute schriftlich festhalten und dem Brandschutzverantwortlichen abgeben.',
    ],
    followUp: [
      'Am Sammelplatz anhand der Klassenliste zählen und das Ergebnis der Evakuationsleitung melden – auch dann, wenn alle da sind.',
      'Fehlende Personen mit letztem bekanntem Aufenthaltsort unverzüglich der Einsatzleitung der Feuerwehr melden.',
      'Schulleitung informiert Erziehungsberechtigte über den offiziellen Kanal; keine Namen von Verletzten über Messenger oder soziale Medien.',
      'Betreuung am Sammelplatz sicherstellen: Betreuungsschlüssel halten, Kinder beschäftigen, bei Kälte in den Ausweichraum verlegen.',
      'Rückkehr ins Gebäude ausschliesslich nach ausdrücklicher Freigabe der Feuerwehr.',
      'Ereignis lückenlos im Protokoll festhalten: Zeitpunkte, Meldungen, Entscheide. Verletzungen von Mitarbeitenden dem Unfallversicherer melden.',
      'Nachbearbeitung mit dem Brandschutzverantwortlichen: Ursache, Ablauf der Räumung, Anpassungen am Evakuationsplan.',
    ],
    checklist: [
      'Feuerwehr 118 alarmiert',
      'App-Alarm für den Standort ausgelöst',
      'Alle Räume geräumt, Türen geschlossen',
      'Klassenlisten am Sammelplatz, Zählung gemeldet',
      'Persönliche Evakuationspläne umgesetzt',
      'Feuerwehr eingewiesen und über Vermisste informiert',
      'Erziehungsberechtigte informiert',
      'Freigabe der Feuerwehr für die Rückkehr erhalten',
      'Ereignis protokolliert, Unfallmeldungen ausgelöst',
    ],
    legalBasis: [
      'VKF-Brandschutzvorschriften, Brandschutzrichtlinie 16-15 «Organisatorischer Brandschutz»: Brandschutzverantwortliche:r, Alarm- und Evakuationsorganisation, jährliche Räumungsübung.',
      'ArGV 4 Art. 27: Fluchtwege müssen jederzeit frei, sicher begehbar und benutzbar sein.',
      'ArGV 3 Art. 36: Der Betrieb stellt Ersthelfende, Material und Notfallorganisation sicher.',
      'StGB Art. 128: Unterlassung der Nothilfe ist strafbar – Hilfe im Rahmen des Zumutbaren ist Pflicht.',
      'Gebäudeversicherung und Feuerpolizei des Kantons Zug: Abnahme, periodische Kontrolle, Vorgaben zu Löscheinrichtungen.',
    ],
  },
  {
    id: 'sc-evak', icon: 'door-open', title: 'Evakuierung', category: 'Gebäude & Technik', priority: 'hoch', silentDefault: false,
    defaultChannels: ['push', 'sms', 'tts'], responsibleGroupIds: ['gr-alle'], contactIds: ['ec-118', 'ec-117'],
    callGuidance: [
      'Die Räumung kann intern angeordnet werden. Ein Notruf ist nötig, wenn ein Ereignis dahintersteht: Brand 118, Bedrohung 117, Verletzte 144.',
      'Melden: Standort und Gebäude, Grund der Räumung, ungefähre Anzahl Personen, Sammelplatz und Zufahrt für die Einsatzkräfte.',
      'Immer erwähnen: Sonderschule mit Kindern, die begleitet oder getragen werden müssen – das bestimmt, wie viele Einsatzkräfte aufgeboten werden.',
      'Hat eine Blaulichtorganisation die Räumung angeordnet, gelten ihre Anweisungen; keine parallelen Aufträge an die Mitarbeitenden.',
    ],
    instructions: [
      'Unterricht oder Therapie sofort beenden. Ruhige, bestimmte Ansage: «Wir gehen jetzt gemeinsam nach draussen.»',
      'Klasse sammeln, anhand der Klassenliste zählen und die Liste mitnehmen.',
      'Schüler:innen mit besonderem Unterstützungsbedarf nach ihrem persönlichen Evakuationsplan begleiten – festgelegte Begleitperson, Tragehilfe, Evakuationsstuhl.',
      'Besucher:innen, Therapiegäste, Praktikant:innen und Handwerker mitnehmen – sie kennen die Wege nicht.',
      'Nächstgelegenen freien Fluchtweg benutzen, geschlossen gehen, keine Aufzüge, keine persönlichen Sachen holen.',
      'Räume kontrollieren (auch WC und Nebenräume), Türe schliessen und nicht abschliessen – so weiss die Einsatzleitung: Raum geräumt.',
      'Am Sammelplatz Abstand zu Zufahrten halten – die Blaulichtorganisationen brauchen freie Wege.',
    ],
    responseSteps: [
      { text: 'Kein zweiter Alarm: Die Räumung ist ausgelöst. Wer sie angeordnet hat, steht in der Meldung.' },
      { text: 'Unterricht oder Therapie sofort beenden. Ruhige, bestimmte Ansage: «Wir gehen jetzt gemeinsam nach draussen.»' },
      { text: 'Klasse sammeln, anhand der Klassenliste zählen, Liste mitnehmen.' },
      { text: 'Schüler:innen mit besonderem Unterstützungsbedarf nach ihrem persönlichen Evakuationsplan begleiten.' },
      { text: 'Evakuationshelfer: zugeteilte Etage abgehen, Räume kontrollieren, Personen mit Evakuationsplan begleiten, danach Vollzug melden.', groupIds: ['gr-evak'] },
      { text: 'Besucher:innen, Therapiegäste und Handwerker mitnehmen – sie kennen die Wege nicht.' },
      { text: 'Nächsten freien Fluchtweg nehmen, keine Aufzüge, nichts holen. Raum kontrollieren, Türe schliessen, nicht abschliessen.' },
      { text: 'Am Sammelplatz zählen und melden: «Klasse X, vollständig» oder «Klasse X, es fehlen N – zuletzt gesehen in …».' },
      { text: 'Hausdienst: Zufahrten freihalten, Einsatzkräfte einweisen, Ausweichräume bei Kälte aufschliessen.', groupIds: ['gr-sicherheit'] },
      { text: 'Rückkehr erst nach Entwarnung über die App oder durch die Einsatzleitung.' },
    ],
    allClearSteps: [
      'Rückkehr erst nach der Freigabe durch die Evakuationsleitung – den Sammelplatz geschlossen als Klasse verlassen.',
      'Klasse im Raum erneut zählen und die Vollständigkeit melden.',
      'Kinder beruhigen: Strukturen und Rituale wieder aufnehmen, Bezugspersonen bleiben bei ihren Schüler:innen.',
      'Eltern nur auf Anweisung der Schulleitung informieren – keine eigenen Mitteilungen.',
      'Rückmeldung zum Ablauf (was hat funktioniert, was nicht) an die Evakuationsleitung.',
    ],
    followUp: [
      'Zählung an die Evakuationsleitung melden, im festen Wortlaut: «Klasse X, vollständig» oder «Klasse X, es fehlen N – zuletzt gesehen in …».',
      'Vermisste sofort der Einsatzleitung melden – niemand geht auf eigene Faust zurück ins Gebäude.',
      'Betreuung organisieren: Betreuungsschlüssel halten, bei Kälte oder Nässe in die vereinbarten Ausweichräume verlegen.',
      'Bei längerer Dauer: Schulleitung organisiert die Abholung über den offiziellen Kanal und dokumentiert, wer welches Kind abholt.',
      'Rückkehr erst nach ausdrücklicher Freigabe der Einsatzleitung.',
      'Ablauf im Protokoll festhalten: Auslöser, Zeitpunkte, Dauer, Besonderheiten, Verbesserungsvorschläge.',
    ],
    checklist: [
      'App-Alarm für den betroffenen Standort ausgelöst',
      'Alle Klassen gezählt, Listen mitgenommen',
      'Persönliche Evakuationspläne umgesetzt',
      'Externe Personen mitgenommen',
      'Räume kontrolliert, Türen geschlossen',
      'Zählung an die Evakuationsleitung gemeldet',
      'Betreuung am Sammelplatz sichergestellt',
      'Freigabe für die Rückkehr erhalten',
    ],
    legalBasis: [
      'VKF-Brandschutzrichtlinie 16-15: Evakuationskonzept, gekennzeichneter Sammelplatz, mindestens jährliche Räumungsübung mit Auswertung.',
      'ArGV 4 Art. 27 und Art. 28: Fluchtwege und Notausgänge, Kennzeichnung, Sicherheitsbeleuchtung.',
      'BehiG Art. 3 und Art. 11: Bauten müssen für Menschen mit Behinderungen zugänglich und im Notfall sicher verlassbar sein – persönliche Evakuationspläne sind das anerkannte Mittel dazu.',
      'Aufsichtspflicht der Schule gegenüber den anvertrauten Kindern; kantonale Schulgesetzgebung Zug.',
      'ArGV 3 Art. 36: Notfallorganisation und Schulung der Mitarbeitenden.',
    ],
  },
  {
    id: 'sc-medizin', icon: 'heart-pulse', title: 'Medizinischer Notfall', category: 'Gesundheit', priority: 'hoch', silentDefault: false,
    defaultChannels: ['push', 'voice'], responsibleGroupIds: ['gr-ersthelfer'], contactIds: ['ec-144', 'ec-145', 'ec-1414'],
    callGuidance: [
      'Sanitätsnotruf 144 anrufen bei gestörtem Bewusstsein oder gestörter Atmung, starker Blutung, Krampfanfall über fünf Minuten, Verdacht auf Vergiftung – und immer dann, wenn Sie unsicher sind. Unsicherheit ist ein Grund zu rufen, kein Grund zu warten.',
      'Melden: Wo genau (Standort, Gebäude, Raum, Zufahrt), was ist passiert, wie viele Betroffene, welche Verletzungen oder Beschwerden, Rückrufnummer.',
      'Alter und Beeinträchtigung der betroffenen Person nennen, dazu bekannte Diagnosen und Medikamente vom Notfallblatt.',
      'Leitung offen halten und den Anweisungen der Notrufzentrale folgen – sie leitet bei Bedarf durch die Wiederbelebung.',
      'Bei Vergiftungsverdacht Tox Info Suisse 145: Substanz, Menge und Zeitpunkt bereithalten.',
      'Bei schwer erreichbarem Ort oder langem Anfahrtsweg zusätzlich Rega 1414.',
    ],
    instructions: [
      'Eigenschutz und Übersicht: Gefahrenquelle beseitigen, weitere Kinder aus dem Bereich führen.',
      'Bewusstsein prüfen (ansprechen, anfassen), dann Atmung prüfen (Kopf überstrecken, 10 Sekunden hören, sehen, fühlen).',
      'Keine Atmung: sofort Herzdruckmassage 30:2 beginnen, Defibrillator holen lassen und anwenden, bis der Rettungsdienst übernimmt.',
      'Bewusstlos mit normaler Atmung: stabile Seitenlage, Atmung laufend kontrollieren, warm halten.',
      'Ansprechbar: beruhigen, hinlegen oder bequem lagern, Blutungen mit Druckverband stillen, nicht allein lassen.',
      'Bei Vergiftungsverdacht nichts zu trinken geben und kein Erbrechen auslösen; Substanz, Verpackung oder Erbrochenes für den Rettungsdienst sicherstellen.',
      'Notfallmedikamente nur nach ärztlicher Verordnung und schriftlicher Ermächtigung der Erziehungsberechtigten verabreichen – Zeitpunkt und Dosis sofort notieren.',
      'Rettungsdienst an der vereinbarten Zufahrt abholen und einweisen.',
    ],
    responseSteps: [
      { text: 'Kein zweiter Notruf: 144 ist alarmiert, sofern die Meldung nichts anderes sagt.' },
      { text: '«Ich komme» quittieren, Notfallrucksack und Defibrillator mitnehmen, direkt zum gemeldeten Ort.', groupIds: ['gr-ersthelfer'] },
      { text: 'Vor Ort übernehmen und von der auslösenden Person erfragen: Was ist passiert, seit wann, was wurde bereits gemacht.', groupIds: ['gr-ersthelfer'] },
      { text: 'Eine Person zur vereinbarten Zufahrt schicken, um den Rettungsdienst einzuweisen.', groupIds: ['gr-ersthelfer', 'gr-sicherheit'] },
      { text: 'Hausdienst: Zufahrt freihalten, Aufzug für den Rettungsdienst bereithalten, Notfallblatt aus dem Sekretariat holen.', groupIds: ['gr-sicherheit'] },
      { text: 'Kinder aus dem Bereich führen, Zugänge freihalten, keine Zuschauer, keine Fotos.' },
      { text: 'Wer nicht in der Nähe ist: nichts unternehmen, erreichbar bleiben.' },
    ],
    allClearSteps: [
      'Die betroffene Person ist versorgt oder übergeben – Ersthelfer räumen auf und ergänzen den Notfallrucksack.',
      'Klasse oder Gruppe beruhigen und den Tagesablauf wieder aufnehmen; Kinder, die den Vorfall miterlebt haben, im Auge behalten.',
      'Ereignisprotokoll noch heute ausfüllen: Zeitpunkt, Massnahmen, beigezogene Dienste.',
      'Erziehungsberechtigte werden durch die Schulleitung oder die zuständige Lehrperson informiert – nicht durch Dritte.',
      'Bei Bedarf ein Gespräch mit der Schulleitung oder dem Care-Team anfordern – auch für Mitarbeitende.',
    ],
    followUp: [
      'Eine Bezugsperson begleitet das Kind ins Spital; Notfallblatt mit Diagnosen, Medikamenten und Allergien mitgeben.',
      'Erziehungsberechtigte umgehend und persönlich informieren – nicht per Nachricht.',
      'Mitschüler:innen altersgerecht informieren und betreuen; Gerüchte im Klassenverband auffangen.',
      'Ereignis mit Zeitangaben dokumentieren: Auffindesituation, Massnahmen, verabreichte Medikamente, beteiligte Personen.',
      'Unfall einer Mitarbeiterin oder eines Mitarbeiters dem Unfallversicherer melden; Schülerunfall der zuständigen Versicherung melden.',
      'Nachbesprechung im Team; bei belastenden Ereignissen Care-Angebot vermitteln.',
      'Notfallrucksack und Defibrillator wieder auffüllen und Einsatzbereitschaft prüfen.',
    ],
    checklist: [
      'Sanitätsnotruf 144 alarmiert',
      'App-Alarm ausgelöst, Ersthelfende vor Ort',
      'Lebensrettende Massnahmen begonnen',
      'Rettungsdienst eingewiesen',
      'Erziehungsberechtigte persönlich informiert',
      'Begleitperson ins Spital bestimmt, Notfallblatt mitgegeben',
      'Ereignis mit Zeiten dokumentiert',
      'Unfallmeldung an die Versicherung ausgelöst',
      'Notfallmaterial wieder aufgefüllt',
    ],
    legalBasis: [
      'StGB Art. 128: Unterlassung der Nothilfe ist strafbar. Erste Hilfe im Rahmen des Zumutbaren ist Pflicht, nicht Ermessen.',
      'ArGV 3 Art. 36: Der Betrieb sorgt für Ersthelfende, Erste-Hilfe-Material und eine geregelte Notfallorganisation.',
      'UVG Art. 45 und UVV: Unfälle von Mitarbeitenden sind dem Unfallversicherer unverzüglich zu melden.',
      'HMG und kantonale Regelungen: Medikamentenabgabe in der Schule nur nach ärztlicher Verordnung und mit schriftlicher Ermächtigung der Erziehungsberechtigten; Abgabe ist zu dokumentieren.',
      'DSG Art. 5: Gesundheitsdaten sind besonders schützenswerte Personendaten – Weitergabe nur an Beteiligte mit Notwendigkeit.',
    ],
  },
  {
    id: 'sc-gewalt', icon: 'hand', title: 'Herausforderndes Verhalten', category: 'Schüler:innen', priority: 'hoch', silentDefault: true,
    defaultChannels: ['push'], responsibleGroupIds: ['gr-paed'], contactIds: ['ec-117'],
    callGuidance: [
      'Hier gilt der stille Alarm: Das Deeskalationsteam wird ohne Ton und ohne Aufsehen aufgeboten. Keine laute Ansage, kein Publikum.',
      'Polizei 117 nur, wenn Waffen im Spiel sind, Dritte unmittelbar gefährdet sind oder die Lage trotz Deeskalation entgleitet.',
      'Beim Notruf sachlich melden: Standort und Zufahrt, wie viele Personen beteiligt sind, ob Waffen vorhanden sind, was bisher versucht wurde.',
      'Ausdrücklich sagen, dass die betroffene Person eine kognitive Beeinträchtigung hat – das verändert das Vorgehen der Polizei vor Ort.',
      'Bei Verletzungen zusätzlich Sanitätsnotruf 144.',
    ],
    instructions: [
      'Andere Schüler:innen aus dem Raum oder aus der Situation führen – Reizreduktion ist die wirksamste Sofortmassnahme.',
      'Eigenschutz: Fluchtweg für sich selbst freihalten, Abstand halten, nicht in die Enge treiben, nicht zwischen Person und Türe stellen.',
      'Ruhige, tiefe Stimme, kurze Sätze, Namen verwenden, keine Diskussion, keine Drohungen und keine Ultimaten.',
      'Reize senken: Lärm, Licht und Zuschauer reduzieren, gewohnte Bezugsperson übernimmt die Kommunikation.',
      'Individuellen Deeskalationsplan der Person anwenden, falls vorhanden – bekannte Auslöser, Signalwörter, Rückzugsort.',
      'Körperliche Intervention nur als letztes Mittel zur Abwehr einer unmittelbaren Gefahr für Leib und Leben – so kurz und so mild wie möglich, nie allein, nie in Bauchlage, Atmung immer im Blick.',
      'Entgleitet die Lage trotz allem: Bereich räumen, sich selbst in Sicherheit bringen und die Polizei beiziehen – siehe Schritt «Alarmieren».',
    ],
    responseSteps: [
      { text: 'Still bleiben: kein Gespräch darüber vor Kindern, keine laute Ansage, nichts in Gruppen-Chats.' },
      { text: 'Quittieren und ohne Aufsehen zum Ort. Höchstens zwei Personen betreten den Raum – mehr Publikum verschärft die Lage.', groupIds: ['gr-paed'] },
      { text: 'Vor der Türe kurz absprechen: Wer spricht, wer sichert den Ausgang, wer übernimmt die übrigen Kinder.', groupIds: ['gr-paed'] },
      { text: 'Eigene Gruppe im Raum behalten, Flur freihalten, Neugierige fernhalten.' },
      { text: 'Ersthelfer: in Bereitschaft bleiben, nicht in den Raum – erst auf Anforderung des Deeskalationsteams.', groupIds: ['gr-ersthelfer'] },
      { text: 'Polizei nur auf Anweisung der Person vor Ort oder der Schulleitung – nicht auf eigene Faust.' },
      { text: 'Entwarnung kommt über die App. Bis dahin bleibt der Bereich gesperrt.' },
    ],
    allClearSteps: [
      'Erst wieder in die Situation, wenn das Deeskalationsteam oder die Schulleitung freigibt.',
      'Betroffene Schüler:innen und Mitarbeitende nicht allein lassen; ruhige Nachbesprechung, keine Sanktionen im Affekt.',
      'Verletzungen medizinisch abklären lassen und melden.',
      'Vorfall im Ereignisprotokoll festhalten (Auslöser, Verlauf, Massnahmen) und der Schulleitung übergeben.',
      'Förderplanung und persönlichen Notfallplan der betroffenen Person zeitnah überprüfen.',
    ],
    followUp: [
      'Nachsorge für die betroffene Person: Rückzugsort, vertraute Bezugsperson, keine Sanktion in der Erregungsphase.',
      'Jede bewegungseinschränkende Massnahme unverzüglich schriftlich protokollieren: wer, was, wann, wie lange, warum, welche milderen Mittel wurden zuerst versucht.',
      'Erziehungsberechtigte und – wo bestellt – die Vertretungsperson noch am selben Tag informieren.',
      'Betroffene Mitschüler:innen und Mitarbeitende betreuen; Verletzungen ärztlich abklären und dem Unfallversicherer melden.',
      'Fallbesprechung im interdisziplinären Team: Auslöser, Verlauf, Wirksamkeit der Massnahmen, Anpassung des Deeskalationsplans.',
      'Bei wiederholten oder schweren Vorfällen: Schulpsychologischen Dienst und behandelnde Fachpersonen einbeziehen; bei Hinweisen auf eine Kindeswohlgefährdung Meldung an die KESB prüfen.',
    ],
    checklist: [
      'Stiller Alarm ausgelöst, Deeskalationsteam vor Ort',
      'Mitschüler:innen in Sicherheit gebracht',
      'Individueller Deeskalationsplan angewendet',
      'Körperliche Intervention nur als letztes Mittel, nie allein',
      'Bewegungseinschränkende Massnahme protokolliert',
      'Erziehungsberechtigte informiert',
      'Verletzungen abgeklärt und gemeldet',
      'Fallbesprechung terminiert, Plan angepasst',
    ],
    legalBasis: [
      'ZGB Art. 383–385: Bewegungseinschränkende Massnahmen bei urteilsunfähigen Personen in Wohn- oder Pflegeeinrichtungen sind nur als letztes Mittel zulässig, müssen protokolliert werden, die Vertretungsperson ist zu informieren und kann die KESB anrufen.',
      'StGB Art. 15 und Art. 17: Notwehr und rechtfertigender Notstand – jede Intervention muss verhältnismässig sein und darf nur so weit gehen, wie zur Abwehr der Gefahr nötig.',
      'ZGB Art. 314c und Art. 314d: Melderecht und – für Personen in amtlicher Tätigkeit – Meldepflicht an die KESB bei Anhaltspunkten für eine Kindeswohlgefährdung.',
      'OR Art. 328 und ArG Art. 6: Fürsorgepflicht des Arbeitgebers – Mitarbeitende sind vor Übergriffen zu schützen, Vorfälle sind zu erfassen und auszuwerten.',
      'EKAS-Richtlinie 6508 und Suva-Vorgaben: Gefährdungsermittlung und Schulung für Betriebe mit erhöhtem Gewaltrisiko.',
    ],
  },
  {
    id: 'sc-person', icon: 'lock-open', title: 'Verdächtige Person auf dem Areal', category: 'Sicherheit', priority: 'hoch', silentDefault: true,
    defaultChannels: ['push'], responsibleGroupIds: ['gr-sicherheit', 'gr-krisenstab'], contactIds: ['ec-117'],
    callGuidance: [
      'Stiller Alarm: Sicherheitsverantwortliche und Krisenstab werden informiert, ohne dass die Person etwas bemerkt.',
      'Polizei 117 bei Bedrohung, Waffen, aggressivem Verhalten, wenn die Person das Areal nicht verlässt oder wenn sie Kinder angesprochen hat.',
      'Melden: Standort und Zufahrt, wo sich die Person aufhält und was sie tut, Beschreibung, ob Waffen sichtbar sind, wie viele Kinder in der Nähe sind.',
      'Erwähnen, dass es sich um eine Schule mit Kindern mit Behinderung handelt.',
      'Rückrufnummer angeben und erreichbar bleiben – die Polizei meldet sich für die Einweisung.',
    ],
    instructions: [
      'Nicht allein eingreifen und die Person nicht festhalten – Beobachten und Melden geht vor Handeln.',
      'Aus sicherer Distanz beobachten und sofort notieren: Geschlecht, ungefähres Alter, Grösse, Statur, Kleidung, Auffälligkeiten, Sprache, Richtung, Fahrzeug mit Kennzeichen.',
      'Kinder unauffällig aus dem Bereich führen, Türen zu Klassenzimmern schliessen, Aussentüren nicht offen stehen lassen.',
      'Höflicher Erstkontakt nur zu zweit und nur bei ungefährlichem Eindruck: freundlich ansprechen, nach dem Anliegen fragen, zum Sekretariat begleiten.',
      'Bei Bedrohung, Waffen, aggressivem Verhalten oder Verweigerung: sofort zurückziehen, in einem abschliessbaren Raum einschliessen und dort bleiben, bis die Polizei eintrifft.',
      'Verlässt die Person das Areal: Fluchtrichtung beobachten, nicht verfolgen.',
    ],
    responseSteps: [
      { text: 'Still bleiben: Die Person darf nichts bemerken. Keine Durchsage, kein Hinauslaufen.' },
      { text: 'Eigene Gruppe im Raum behalten, Türe schliessen, Fenster im Erdgeschoss schliessen, Aussentüren nicht öffnen.' },
      { text: 'Kinder nicht auf den Flur oder ins Freie lassen; Pausen und Raumwechsel verschieben, bis Entwarnung kommt.' },
      { text: 'Quittieren, Kontakt zur auslösenden Person aufnehmen, Beschreibung und Aufenthaltsort der Person übernehmen.', groupIds: ['gr-sicherheit'] },
      { text: 'Aussentüren kontrollieren und schliessen, Empfang besetzen, Zufahrt im Blick behalten; niemand geht der Person nach.', groupIds: ['gr-sicherheit'] },
      { text: 'Krisenstab: quittieren, Lage mit dem Hausdienst abstimmen, über Polizeiaufgebot und Elterninformation entscheiden.', groupIds: ['gr-krisenstab'] },
      { text: 'Bei unmittelbarer Bedrohung im eigenen Bereich: Raum abschliessen, Polizei 117, drinnen bleiben.' },
      { text: 'Normalbetrieb erst nach Entwarnung über die App.' },
    ],
    allClearSteps: [
      'Normalbetrieb erst nach Freigabe durch Hausdienst oder Schulleitung – Türen wieder gemäss Tagesregelung.',
      'Beobachtungen (Beschreibung, Zeit, Ort, Verhalten) schriftlich festhalten, solange die Erinnerung frisch ist.',
      'Schüler:innen ohne Dramatisierung informieren, falls sie etwas mitbekommen haben.',
      'Zutrittsregelung und Besucherprozess mit dem Hausdienst überprüfen.',
    ],
    followUp: [
      'Beobachtungen sofort schriftlich festhalten, solange die Erinnerung frisch ist – jede Person für sich, ohne Absprache untereinander.',
      'Schulleitung entscheidet über eine Strafanzeige wegen Hausfriedensbruch und über ein schriftliches Hausverbot.',
      'Mitarbeitende und, wo nötig, Erziehungsberechtigte sachlich informieren – keine Spekulationen, keine Fotos in Umlauf bringen.',
      'Zugangswege überprüfen: Aussentüren, Zeiten, Beschilderung, Empfangsregelung für Besuchende.',
      'Bei wiederholten Vorfällen Kontakt mit der Kantonspolizei Zug zur Beratung aufnehmen.',
    ],
    checklist: [
      'Stiller Alarm ausgelöst',
      'Kinder aus dem Bereich geführt, Türen geschlossen',
      'Personenbeschreibung notiert',
      'Polizei 117 informiert, sofern Bedrohung bestand',
      'Beobachtungen schriftlich festgehalten',
      'Entscheid über Anzeige und Hausverbot getroffen',
      'Zugangsregelung überprüft',
    ],
    legalBasis: [
      'StGB Art. 186: Hausfriedensbruch – das Hausrecht liegt bei der Trägerschaft; ein Hausverbot ist schriftlich auszusprechen.',
      'StPO Art. 218: Eine vorläufige Festnahme durch Private ist nur beim Betreffen auf frischer Tat und nur bei Verbrechen oder Vergehen zulässig. Im Schulalltag gilt: nicht eingreifen, Polizei rufen.',
      'OR Art. 328 und ArG Art. 6: Fürsorgepflicht des Arbeitgebers – Mitarbeitende dürfen nicht in gefährliche Situationen geschickt werden.',
      'DSG Art. 6 und Art. 25 ff.: Personenbeschreibungen und allfällige Videoaufnahmen sind Personendaten; Aufnahmen nur mit erkennbarer Kennzeichnung, Weitergabe nur an die Polizei.',
      'Aufsichtspflicht der Schule: Schutz der anvertrauten Kinder hat Vorrang vor der Klärung des Sachverhalts.',
    ],
  },
  {
    id: 'sc-todesfall', icon: 'heart-crack', title: 'Todesfall', category: 'Organisation', priority: 'hoch', silentDefault: true,
    defaultChannels: ['push', 'voice'], responsibleGroupIds: ['gr-krisenstab'], contactIds: ['ec-144', 'ec-117', 'ec-143'],
    callGuidance: [
      'Bei einer leblosen Person zuerst mit der Wiederbelebung beginnen und Sanitätsnotruf 144 anrufen – den Tod stellt ausschliesslich eine Ärztin oder ein Arzt fest, nie Mitarbeitende.',
      'Melden: Wo genau, was vorgefallen ist, seit wann die Person leblos ist, ob mit der Wiederbelebung begonnen wurde, Rückrufnummer.',
      'Bei einem aussergewöhnlichen Todesfall – Unfall, Suizid, Gewalt oder unklare Ursache – zusätzlich Polizei 117 und deren Anweisungen abwarten.',
      'Der stille Alarm bietet den Krisenstab auf, ohne dass Kinder etwas mitbekommen.',
      'Keine Auskunft an Angehörige, Externe oder Medien am Telefon: Die Angehörigen werden persönlich und abgestimmt informiert.',
    ],
    instructions: [
      'Solange kein Arzt den Tod festgestellt hat, gilt die Person als lebend: Wiederbelebung ohne Unterbrechung fortführen, bis der Rettungsdienst übernimmt.',
      'Ist der Tod ärztlich festgestellt: Fundort unverändert lassen, nichts wegräumen, nichts reinigen, niemanden hineinlassen.',
      'Bei einem aussergewöhnlichen Todesfall die Anweisungen der Polizei abwarten und den Bereich für sie freihalten.',
      'Kinder und Jugendliche aus dem Bereich führen und lückenlos betreuen; niemanden allein lassen.',
      'Handyverbot im betroffenen Bereich durchsetzen – keine Fotos, keine Nachrichten, keine Beiträge in sozialen Medien.',
      'Die Sprachregelung legt ausschliesslich die Schulleitung fest. Bis dahin gilt gegenüber allen Externen und Medien: keine Auskunft.',
    ],
    responseSteps: [
      { text: 'Still bleiben: nichts weitererzählen, nichts posten, keine Nachrichten an Kolleg:innen oder Eltern.' },
      { text: 'Quittieren, Führungsraum beziehen, Sprachregelung festlegen; Care-Team und Schulpsychologischen Dienst aufbieten.', groupIds: ['gr-krisenstab'] },
      { text: 'Fundort unverändert lassen und den Bereich sperren; bei aussergewöhnlichem Todesfall auf die Polizei warten.', groupIds: ['gr-krisenstab', 'gr-sicherheit'] },
      { text: 'Unterricht so normal wie möglich fortführen; den betroffenen Bereich nicht betreten und keine Kinder hinlassen.' },
      { text: 'Fragen von Kindern oder Eltern: «Die Schulleitung informiert.» – nicht mehr.' },
      { text: 'Medienanfragen unbeantwortet an die von der Schulleitung bezeichnete Stelle weiterleiten.' },
      { text: 'Weitere Weisungen kommen über die App oder persönlich von der Schulleitung.' },
    ],
    allClearSteps: [
      'Anweisungen des Krisenstabs zur Information der Klassen und Eltern abwarten – keine eigenen Mitteilungen.',
      'Betroffene Schüler:innen und Mitarbeitende begleiten; Care-Team beiziehen, Rückzugsraum anbieten.',
      'Auf sich selbst achten: Unterstützung annehmen, Gespräch mit der Schulleitung oder dem Care-Team.',
      'Tagesstruktur behutsam wieder aufnehmen; Rituale und Gedenken gemäss Vorgabe des Krisenstabs.',
    ],
    followUp: [
      'Angehörige werden zuerst und persönlich informiert – nie über die Schule und nie vor der Polizei, wenn diese eingeschaltet ist.',
      'Erst danach das Team informieren, dann die betroffene Klasse, dann die übrige Schule – in dieser Reihenfolge und mit abgestimmtem Wortlaut.',
      'Care-Team und Schulpsychologischen Dienst aufbieten; Betreuungsangebot für Kinder und Mitarbeitende einrichten.',
      'Zivilstandsamt: Der Todesfall ist innert zweier Tage zu melden – bei einem Todesfall in der Institution klärt die Schulleitung die Zuständigkeit mit den Angehörigen.',
      'Rituale ermöglichen: Kerze, Kondolenzbuch, Platz im Klassenzimmer, Beteiligung an der Abdankung nach Absprache mit den Angehörigen.',
      'Medienanfragen ausschliesslich über die von der Schulleitung bezeichnete Stelle beantworten.',
      'Nachsorge über Wochen planen: Jahrestage, Rückkehr in den Alltag, längerfristige Begleitung einzelner Kinder.',
      'Bei Suizid: zurückhaltende, nicht verherrlichende Kommunikation nach den Empfehlungen zur Suizidprävention; besonders gefährdete Mitschüler:innen im Blick behalten.',
    ],
    checklist: [
      'Rettungsdienst 144 alarmiert, Wiederbelebung begonnen',
      'Krisenstab aufgeboten',
      'Bei aussergewöhnlichem Todesfall: Polizei 117 verständigt, Fundort unverändert',
      'Kinder betreut, Bereich geräumt',
      'Angehörige persönlich informiert',
      'Sprachregelung durch die Schulleitung festgelegt',
      'Care-Team und Schulpsychologischer Dienst aufgeboten',
      'Meldung an das Zivilstandsamt geklärt',
      'Nachsorge über die kommenden Wochen geplant',
    ],
    legalBasis: [
      'StPO Art. 253: Bei aussergewöhnlichem Todesfall – Unfall, Suizid, Gewalteinwirkung oder unklare Ursache – sind Polizei und Staatsanwaltschaft zu benachrichtigen; Leichnam und Fundort dürfen bis zur Freigabe nicht verändert werden.',
      'StGB Art. 128: Bis zur ärztlichen Feststellung des Todes gilt die Pflicht zur Nothilfe.',
      'Zivilstandsverordnung Art. 34 f.: Der Tod ist innert zweier Tage der Zivilstandsbehörde des Sterbeorts zu melden; Grundlage ist die ärztliche Todesbescheinigung.',
      'DSG Art. 5 und Art. 6: Angaben zu Verstorbenen und Angehörigen sind Personendaten – keine Weitergabe von Namen an Dritte oder Medien ohne Einwilligung der Angehörigen.',
      'Kanton Zug: Aufgebot des kantonalen Care-Teams über die Einsatzleitzentrale; Schulpsychologischer Dienst als schulische Anlaufstelle.',
    ],
  },
  {
    id: 'sc-wasserunfall', icon: 'droplets', title: 'Notfall im Therapiebad', category: 'Gesundheit', priority: 'hoch', silentDefault: false,
    defaultChannels: ['push', 'voice'], responsibleGroupIds: ['gr-ersthelfer'], contactIds: ['ec-144', 'ec-1414'],
    callGuidance: [
      'Laut um Hilfe rufen – die Rettung aus dem Wasser darf für das Alarmieren nicht unterbrochen werden. Wer zu zweit ist, teilt auf: eine Person rettet, die andere alarmiert.',
      'Sanitätsnotruf 144 bei jedem Ertrinkungsnotfall, auch wenn die Person wieder atmet.',
      'Melden: Therapiebad und Standort, was passiert ist, wie lange die Person unter Wasser war, ob sie atmet, ob mit der Beatmung begonnen wurde.',
      'Die Zufahrt zum Bad genau beschreiben und jemanden zur Einweisung abstellen – der Weg ist von aussen nicht selbsterklärend.',
      'Bei schwerer Erreichbarkeit oder langem Anfahrtsweg zusätzlich Rega 1414.',
    ],
    instructions: [
      'Person sofort aus dem Wasser holen. Rettung von aussen mit Rettungsstange oder Gurtretter hat Vorrang – nur ins Wasser springen, wenn es anders nicht geht.',
      'Alle übrigen Kinder unverzüglich aus dem Becken holen und am Beckenrand sammeln – nie unbeaufsichtigt im Wasser lassen.',
      'Atmung prüfen. Keine normale Atmung: sofort mit fünf Beatmungen beginnen, dann Herzdruckmassage 30:2 – beim Ertrinken steht der Sauerstoffmangel im Vordergrund.',
      'Defibrillator anwenden: Brustkorb vorher abtrocknen, Person nicht auf nasser Fläche liegen lassen.',
      'Bewusstlos mit normaler Atmung: stabile Seitenlage, Wärmeerhalt mit Rettungsdecke, Atmung laufend kontrollieren.',
      'Auch bei scheinbar unauffälliger Person nach Wasseraspiration: ärztliche Abklärung ist zwingend – Beschwerden können Stunden später auftreten.',
      'Bei Verdacht auf Wirbelsäulenverletzung nach Sprung oder Sturz: Kopf und Nacken achsengerecht stabilisieren, so wenig wie möglich bewegen.',
    ],
    responseSteps: [
      { text: 'Kein zweiter Notruf: 144 ist alarmiert.' },
      { text: '«Ich komme» quittieren, Notfallrucksack und Defibrillator mitnehmen, direkt ins Bad.', groupIds: ['gr-ersthelfer'] },
      { text: 'Vor Ort die Wiederbelebung übernehmen und im Wechsel weiterführen – alle zwei Minuten abwechseln; Brustkorb vor dem Defibrillator abtrocknen.', groupIds: ['gr-ersthelfer'] },
      { text: 'Zur Zufahrt zum Bad, um den Rettungsdienst einzuweisen – der Weg ist von aussen nicht selbsterklärend.', groupIds: ['gr-sicherheit'] },
      { text: 'Übrige Kinder in den Trockenbereich, abtrocknen, warm halten, betreuen; niemand zurück ins Wasser.' },
      { text: 'Wer nicht in der Nähe ist: nichts unternehmen, erreichbar bleiben.' },
    ],
    allClearSteps: [
      'Der Badbetrieb bleibt gesperrt, bis Badeaufsicht und Schulleitung freigeben.',
      'Beteiligte Kinder in Ruhe umziehen, wärmen und beobachten – Beschwerden können bis 24 Stunden später auftreten; Eltern auf Warnzeichen hinweisen.',
      'Ereignisprotokoll (Zeiten, Massnahmen, Beteiligte) ausfüllen und der Schulleitung übergeben.',
      'Bad- und Aufsichtskonzept mit der Badeaufsicht überprüfen.',
    ],
    followUp: [
      'Betrieb des Bades bis zur Klärung einstellen und den Zugang sperren.',
      'Erziehungsberechtigte umgehend persönlich informieren; eine Bezugsperson begleitet ins Spital.',
      'Ereignis genau dokumentieren: Zeitpunkt, Aufsichtssituation, Anzahl Kinder im Wasser, Wassertiefe, Massnahmen, beteiligte Personen.',
      'Unfallmeldung an die Versicherung; bei Mitarbeitenden zusätzlich an den Unfallversicherer.',
      'Aufsichtskonzept überprüfen: Betreuungsschlüssel, Qualifikation der Aufsicht, Sichtverhältnisse, Rettungsmittel, Alarmierungsweg.',
      'Mitbetroffene Kinder und Mitarbeitende betreuen; Wiedereinstieg ins Wasser behutsam gestalten.',
      'Bei technischer Ursache – Absaugung, Rutsche, Hubboden – Anlage prüfen lassen und bis zur Freigabe gesperrt halten.',
    ],
    checklist: [
      'Person aus dem Wasser, alle anderen Kinder aus dem Becken',
      'App-Alarm ausgelöst, Ersthelfende vor Ort',
      'Sanitätsnotruf 144 alarmiert',
      'Beatmung und Herzdruckmassage nach Ertrinkungsschema begonnen',
      'Defibrillator eingesetzt, Untergrund trocken',
      'Wärmeerhalt sichergestellt',
      'Ärztliche Abklärung veranlasst, auch bei unauffälliger Person',
      'Bad gesperrt, Ereignis dokumentiert',
      'Aufsichtskonzept überprüft',
    ],
    legalBasis: [
      'bfu-Fachdokumentation zu Bädern und SIA 385/1 «Anlagen für Badewasser»: Anforderungen an Aufsicht, Rettungsmittel, Alarmierung und Beckengestaltung.',
      'SLRG-Empfehlung: Aufsichtspersonen in Bädern mit Aufsichtspflicht verfügen über ein gültiges Rettungsbrevet; die Qualifikation ist periodisch aufzufrischen.',
      'StGB Art. 128: Unterlassung der Nothilfe; ergänzend StGB Art. 125 – fahrlässige Körperverletzung bei Verletzung der Aufsichtspflicht.',
      'ArGV 3 Art. 36: Ersthelfende, Notfallmaterial und geregelte Alarmierung im Betrieb.',
      'Erhöhte Sorgfalts- und Aufsichtspflicht gegenüber Menschen mit Behinderung: Betreuungsschlüssel und Aufsichtskonzept sind schriftlich festzulegen und einzuhalten.',
    ],
  },
  {
    id: 'sc-it', icon: 'server-crash', title: 'ICT-Ausfall / Cyberangriff', category: 'Gebäude & Technik', priority: 'hoch', silentDefault: false,
    defaultChannels: ['push', 'email', 'teams'], responsibleGroupIds: ['gr-it', 'gr-krisenstab'], contactIds: ['ec-117'],
    callGuidance: [
      'Ein Ausfall allein ist kein Fall für 112, 117 oder 144 – der Notruf gilt nur, wenn zusätzlich Personen gefährdet sind.',
      'Zuerst intern alarmieren: ICT-Verantwortliche und Krisenstab werden über den Alarm informiert.',
      'Fällt die App selbst aus, gilt die ausgedruckte Telefonliste im Sekretariat. Die Notrufnummern gehen über das Mobilnetz und sind vom Ausfall nicht betroffen.',
      'Keine technischen Angaben, Zugangsdaten oder Bildschirmfotos an Unbekannte weitergeben – auch nicht an angebliche Support-Anrufe.',
      'Meldung an das Bundesamt für Cybersicherheit und eine Strafanzeige vorbereiten; entschieden wird im Krisenstab.',
    ],
    instructions: [
      'Bei Verdacht auf einen Angriff – Lösegeldforderung, verschlüsselte Dateien, unbekannte Zugriffe – betroffene Geräte sofort vom Netz trennen: Netzwerkkabel ziehen, WLAN ausschalten.',
      'Geräte nicht ausschalten und nichts löschen – im Arbeitsspeicher liegen Spuren, die für die Aufklärung gebraucht werden.',
      'Reines Ausfallereignis ohne Angriffsverdacht: Umfang feststellen – einzelnes Gerät, Standort oder alle Standorte, welche Dienste betroffen.',
      'Auf Papierbetrieb umstellen: Klassenlisten, Notfallblätter, Telefonlisten und Medikamentenpläne liegen ausgedruckt im Sekretariat.',
      'Sicherstellen, dass Alarmierung und Erreichbarkeit unabhängig funktionieren: Mobiltelefone, Notrufnummern 112/117/118/144 gehen über das Mobilnetz.',
      'Keine Lösegeldzahlung und keine eigenmächtigen Wiederherstellungsversuche – Entscheide trifft der Krisenstab zusammen mit den ICT-Verantwortlichen.',
      'Passwörter erst nach Absprache ändern; überstürzte Änderungen können Spuren zerstören oder Angreifer warnen.',
    ],
    responseSteps: [
      { text: 'Keine eigenen Reparaturversuche: nichts neu starten, keine Passwörter ändern, nichts löschen – Anweisungen der ICT abwarten.' },
      { text: 'Quittieren, betroffene Geräte vom Netz nehmen, nicht ausschalten, Spuren sichern; Umfang feststellen.', groupIds: ['gr-it'] },
      { text: 'Krisenstab: Lage mit der ICT aufnehmen, über Meldungen an Datenschutzaufsicht, BACS und Polizei entscheiden.', groupIds: ['gr-krisenstab'] },
      { text: 'Auf Papierbetrieb umstellen. Klassenlisten, Notfallblätter, Telefonlisten und Medikamentenpläne liegen im Sekretariat.' },
      { text: 'Erreichbarkeit über das Mobiltelefon sicherstellen; die Notrufnummern gehen über das Mobilnetz.' },
      { text: 'Verdächtige E-Mails oder Anrufe von angeblichem Support: nicht reagieren, der ICT melden.' },
      { text: 'Nichts nach aussen kommunizieren – das macht der Krisenstab.' },
    ],
    allClearSteps: [
      'Systeme erst wieder normal nutzen, wenn die IT die Freigabe gibt – auch wenn etwas wieder zu funktionieren scheint.',
      'Passwort ändern, falls die IT dazu auffordert; verdächtige Mails oder Geräte melden statt selbst prüfen.',
      'Während des Ausfalls auf Papier erfasste Daten nachtragen.',
      'Notierte Auffälligkeiten (Zeitpunkt, Fehlermeldung, betroffene Geräte) der IT melden.',
    ],
    followUp: [
      'Betroffene Systeme, Zeitpunkte und Auffälligkeiten protokollieren; Ereignisprotokolle und Sicherungen sichern.',
      'Prüfen, ob Personendaten betroffen sind. Ist ein hohes Risiko für die betroffenen Personen wahrscheinlich, ist die Verletzung der Datensicherheit der zuständigen Datenschutzaufsicht so rasch als möglich zu melden.',
      'Betroffene Personen informieren, wenn es zu ihrem Schutz nötig ist oder die Aufsichtsbehörde es verlangt.',
      'Vorfall dem Bundesamt für Cybersicherheit melden – für Schulen freiwillig, aber empfohlen; die Meldung hilft, weitere Angriffe einzuordnen.',
      'Strafanzeige bei der Kantonspolizei Zug prüfen; Beweismittel bis dahin unverändert aufbewahren.',
      'Wiederherstellung nur aus geprüften, offline gehaltenen Sicherungen und erst nach Bereinigung der Systeme.',
      'Erziehungsberechtigte und Mitarbeitende sachlich informieren, sobald der Sachverhalt gesichert ist.',
      'Nachbearbeitung: Wiederherstellungszeiten, Lücken im Notbetrieb, Schulung der Mitarbeitenden, Prüfung der Sicherungsstrategie.',
    ],
    checklist: [
      'Betroffene Geräte vom Netz getrennt, nicht ausgeschaltet',
      'App-Alarm ausgelöst, ICT und Krisenstab informiert',
      'Umfang des Ausfalls festgestellt',
      'Papierbetrieb aufgenommen, Notfallunterlagen verfügbar',
      'Alarmierung über Mobilnetz sichergestellt',
      'Betroffenheit von Personendaten geprüft',
      'Meldung an die Datenschutzaufsicht geprüft und dokumentiert',
      'Meldung an das Bundesamt für Cybersicherheit erwogen',
      'Wiederherstellung aus geprüfter Sicherung',
    ],
    legalBasis: [
      'DSG Art. 24: Verletzungen der Datensicherheit sind dem Eidgenössischen Datenschutz- und Öffentlichkeitsbeauftragten so rasch als möglich zu melden, wenn ein hohes Risiko für die betroffenen Personen wahrscheinlich ist; betroffene Personen sind zu informieren, soweit es zu ihrem Schutz nötig ist.',
      'DSG Art. 8 und DSV: angemessene technische und organisatorische Massnahmen zur Datensicherheit, einschliesslich Sicherungen und Zugriffskontrolle.',
      'Kanton Zug: Ist die Trägerschaft ein öffentliches Organ, gilt das kantonale Datenschutzgesetz mit der kantonalen Aufsichtsstelle statt des DSG – die Zuständigkeit ist vorab schriftlich zu klären.',
      'ISG und Cybersicherheitsverordnung: Meldepflicht für Betreiber kritischer Infrastrukturen an das Bundesamt für Cybersicherheit. Schulen fallen in der Regel nicht darunter, die freiwillige Meldung steht offen.',
      'StGB Art. 143bis und Art. 144bis: unbefugtes Eindringen in Datenverarbeitungssysteme und Datenbeschädigung sind Straftaten – Strafanzeige ist möglich, Beweismittel sind zu sichern.',
    ],
  },
  {
    id: 'sc-krise', icon: 'users', title: 'Krisenstab einberufen', category: 'Organisation', priority: 'hoch', silentDefault: false,
    defaultChannels: ['push', 'sms', 'voice', 'conference'], responsibleGroupIds: ['gr-krisenstab'], contactIds: ['ec-117', 'ec-118', 'ec-144'],
    callGuidance: [
      'Einberufen wird bei jedem Ereignis, das eine einzelne Lehrperson oder Gruppenleitung überfordert, mehrere Standorte betrifft, Medieninteresse auslöst oder länger als einen Tag nachwirkt.',
      'Das Aufgebot läuft mit Quittierung: Jedes Mitglied meldet zurück, ob und wann es kommt.',
      'Wer nicht quittiert, wird telefonisch nachgefasst – die Standorttelefonliste liegt ausgedruckt im Führungsraum.',
      'Der Notruf gehört zum auslösenden Ereignis, nicht zum Aufgebot: Läuft bereits ein Einsatz, ist 117/118/144 alarmiert – sonst zuerst dort melden.',
      'Bei Ereignissen, welche die Institution übersteigen, Verbindung zum kantonalen Führungsstab Zug aufnehmen. Anweisungen der Einsatzleitung haben Vorrang.',
    ],
    instructions: [
      'Führungsraum beziehen: Sitzungszimmer Hauptsitz Baar, Rückfallort nach Absprache. Wandprotokoll und Standorttelefonliste bereitlegen.',
      'Lage in fünf Sätzen festhalten: Was ist passiert, wo, seit wann, wer ist betroffen, was ist bereits veranlasst.',
      'Rollen sofort verteilen und laut benennen: Leitung, Journalführung, Kommunikation nach aussen, Kontakt zu den Blaulichtorganisationen, Betreuung, Ablösung.',
      'Journal ab der ersten Minute führen: Uhrzeit, Meldung, Entscheid, Auftrag, Erledigung. Jeder Entscheid mit Zeitstempel.',
      'Sofortmassnahmen festlegen und mit Frist und Namen verbindlich zuweisen; danach den nächsten Lagerapport terminieren.',
      'Eine einzige Sprachregelung beschliessen. Alle Auskünfte nach aussen laufen über die bezeichnete Stelle – niemand sonst gibt Auskunft.',
    ],
    responseSteps: [
      { text: 'Quittieren – auch wenn Sie nicht kommen können. Die Leitung muss wissen, mit wem sie rechnen kann.', groupIds: ['gr-krisenstab'] },
      { text: 'Führungsraum beziehen: Sitzungszimmer Hauptsitz Baar, Rückfallort nach Absprache.', groupIds: ['gr-krisenstab'] },
      { text: 'Unterwegs keine Auskünfte, keine Nachrichten in Gruppen-Chats, keine Anrufe an Eltern.', groupIds: ['gr-krisenstab'] },
      { text: 'Beim Eintreffen: Lage abholen, Rolle übernehmen, sich ins Journal eintragen lassen.', groupIds: ['gr-krisenstab'] },
      { text: 'Wer nicht zum Krisenstab gehört: nichts unternehmen, Weisungen kommen über die App.' },
    ],
    allClearSteps: [
      'Der Krisenstab ist aufgelöst – die Zuständigkeiten gehen zurück an die Linie.',
      'Beschlossene Massnahmen gemäss Protokoll umsetzen; Fristen und Verantwortliche sind dort festgehalten.',
      'Kommunikation nach aussen bleibt bei der Schulleitung.',
      'Nachbesprechung innerhalb von zwei Wochen: Was hat funktioniert, was wird angepasst.',
    ],
    followUp: [
      'Erziehungsberechtigte über den offiziellen Kanal informieren; Eltern-Hotline oder Informationsseite einrichten, bevor Gerüchte entstehen.',
      'Bei Ereignissen mit Beteiligung der Blaulichtorganisationen: Verbindung zur Einsatzleitung halten, keine parallelen Anweisungen an die Mitarbeitenden.',
      'Bei Ereignissen über die Institution hinaus Kontakt zum kantonalen Führungsstab Zug aufnehmen und die Zuständigkeiten klären.',
      'Ablösung und Verpflegung nach spätestens acht Stunden organisieren – ein erschöpfter Stab trifft schlechte Entscheide.',
      'Betreuung sicherstellen: Care-Team, Schulpsychologischer Dienst, seelsorgerliche Begleitung.',
      'Übergang in den Normalbetrieb bewusst und angekündigt vollziehen; den Zeitpunkt der Auflösung im Journal festhalten.',
      'Innert zweier Wochen Auswertung mit allen Beteiligten; Erkenntnisse in Notfallkonzept, Szenarien und Alarmpläne einarbeiten.',
    ],
    checklist: [
      'Aufgebot mit Quittierung ausgelöst',
      'Führungsraum bezogen, Stab vollzählig',
      'Lage in fünf Sätzen festgehalten',
      'Rollen verteilt und benannt',
      'Journal ab der ersten Minute geführt',
      'Sofortmassnahmen mit Frist und Namen zugewiesen',
      'Sprachregelung beschlossen, Auskunftsstelle bezeichnet',
      'Erziehungsberechtigte informiert',
      'Ablösung organisiert',
      'Auswertung terminiert',
    ],
    legalBasis: [
      'ArGV 3 Art. 36: Der Betrieb hält eine Notfallorganisation bereit und schult die Mitarbeitenden darin.',
      'EKAS-Richtlinie 6508: Sicherheitssystem mit klaren Zuständigkeiten, Notfallplanung und regelmässiger Überprüfung.',
      'Kanton Zug: Bei Ereignissen, welche die Institution übersteigen, führt die Einsatzleitung der Blaulichtorganisationen; der kantonale Führungsstab koordiniert. Anweisungen der Einsatzleitung haben Vorrang.',
      'DSG Art. 5 und Art. 6: In der Krisenkommunikation dürfen nur die Personendaten weitergegeben werden, die für den Schutz der Betroffenen nötig sind.',
      'Dokumentationspflicht: Das Journal dient der Rechenschaft gegenüber Aufsicht, Versicherern und Strafverfolgungsbehörden und ist entsprechend aufzubewahren.',
    ],
  },
  {
    id: 'sc-epilepsie', icon: 'activity', title: 'Krampfanfall / Epilepsie', category: 'Gesundheit', priority: 'hoch', active: false, silentDefault: false,
    defaultChannels: ['push', 'voice'], responsibleGroupIds: ['gr-ersthelfer'], contactIds: ['ec-144'],
    instructions: [
      'Uhrzeit merken – die Anfallsdauer entscheidet über den Notruf.',
      'Gefährliche Gegenstände wegräumen, Kopf weich lagern (Jacke/Kissen).',
      'Nicht festhalten, nichts in den Mund geben, nichts einflössen.',
      'Schulsanität per App alarmieren – sie bringt die Notfallmedikation des Kindes.',
      'Notfallmedikation nur gemäss individuellem Notfallplan und nur durch instruierte Personen.',
      '144 anrufen, wenn: Anfall > 5 Minuten, zweiter Anfall, Verletzung, oder kein Notfallplan vorhanden.',
      'Nach dem Anfall: stabile Seitenlage, zudecken, ruhig ansprechen, nicht allein lassen.',
    ],
    followUp: [
      'Eltern/Erziehungsberechtigte noch am selben Tag informieren.',
      'Anfall im Anfallsprotokoll des Kindes dokumentieren (Beginn, Dauer, Verlauf, Medikation).',
      'Mitschüler:innen altersgerecht auffangen – kurz erklären, entdramatisieren.',
    ],
    checklist: ['Anfallsbeginn notiert', 'Umgebung gesichert', 'Notfallplan angewendet', 'Medikationsgabe dokumentiert', '144 beurteilt', 'Eltern informiert', 'Anfallsprotokoll ergänzt'],
  },
  {
    id: 'sc-allergie', icon: 'stethoscope', title: 'Allergische Reaktion / Anaphylaxie', category: 'Gesundheit', priority: 'hoch', active: false, silentDefault: false,
    defaultChannels: ['push', 'voice'], responsibleGroupIds: ['gr-ersthelfer'], contactIds: ['ec-144', 'ec-145'],
    instructions: [
      'Kontakt mit dem Auslöser sofort beenden (Essen weg, Stachel entfernen).',
      'Allergie-Notfallplan des Kindes holen – er hängt im Klassenordner/Sekretariat.',
      'Schulsanität per App alarmieren.',
      'Atemnot, Schwellung im Gesicht oder Kreislaufprobleme? Adrenalin-Autoinjektor (EpiPen) in den äusseren Oberschenkel – nur instruierte Personen – und sofort 144.',
      'Hinlegen, Beine hoch; bei Atemnot sitzend lagern. Zudecken und beruhigen.',
      'Zweite Dosis nach 5–10 Minuten, wenn keine Besserung und zweiter Pen vorhanden.',
    ],
    followUp: [
      'Eltern/Erziehungsberechtigte sofort informieren – nach EpiPen-Gabe immer Spitalkontrolle.',
      'Verabreichte Medikation mit Uhrzeit dokumentieren, Pen ersetzen lassen.',
      'Auslöser-Abklärung mit Küche und Umfeld einleiten (Menüplan, Znüni-Regeln).',
    ],
    checklist: ['Auslöser entfernt', 'Notfallplan angewendet', 'EpiPen dokumentiert', '144 alarmiert', 'Eltern informiert', 'Pen ersetzt', 'Auslöser abgeklärt'],
  },
  {
    id: 'sc-vermisst', icon: 'search', title: 'Vermisste:r Schüler:in / Weglaufen', category: 'Schüler:innen', priority: 'hoch', silentDefault: false,
    defaultChannels: ['push', 'sms'], responsibleGroupIds: ['gr-alle'], contactIds: ['ec-117'],
    callGuidance: [
      'Zuerst den Suchalarm in der App auslösen – alle am Standort erhalten Beschreibung und Suchauftrag. In der Meldung: Name, Alter, Kleidung, letzter Ort und Zeit.',
      'Polizei 117 sofort anrufen, wenn das Kind in Gefahr ist (Gewässer, Bahn, Strasse in der Nähe, Weglauftendenz bekannt, kalte Witterung) – sonst spätestens nach 15 Minuten ohne Erfolg.',
      'Melden: Name und Alter, Beschreibung und Kleidung, letzter Ort und Zeit, Besonderheiten (spricht nicht, reagiert nicht auf Zuruf, Lieblingsorte, Medikamente).',
      'Ausdrücklich sagen: Kind mit Beeinträchtigung aus einer Sonderschule – es kann sich nicht selbst helfen.',
      'Leitung offen halten und eine Rückrufnummer nennen, die während der Suche besetzt bleibt.',
    ],
    instructions: [
      'Uhrzeit notieren: Wann und wo wurde das Kind zuletzt gesehen?',
      'Beschreibung durchgeben: Kleidung, Aussehen, Verhaltensmuster (Weglauftendenz, reagiert nicht auf Zuruf, Lieblingsorte).',
      'Gefahrenstellen zuerst absuchen: Strasse, Bushaltestelle, Gewässer, Bahngleise.',
      'Danach systematisch: Gebäude (WC, Verstecke, Keller), Aussenareal, bekannte Rückzugsorte.',
      'Aufsicht der übrigen Kinder lückenlos sicherstellen, bevor Personal zur Suche abgezogen wird.',
      'Suchprotokoll beginnen: wer sucht wo, seit wann – Doppelspurigkeit vermeiden.',
    ],
    responseSteps: [
      { text: 'Beschreibung aus der Meldung merken: Name, Kleidung, letzter Ort. Sofort die eigene Umgebung prüfen – Raum, Gang, WC, Garderobe.' },
      { text: 'Eigene Klasse zählen und zusammenhalten; niemand verlässt die Gruppe. Wer Kinder betreut, sucht nicht selbst, sondern hält die Augen offen.' },
      { text: 'Ohne Betreuungsaufgabe: bei der Suchleitung melden und einen Bereich übernehmen – nicht auf eigene Faust losgehen.' },
      { text: 'Fund oder Sichtung sofort über die App-Meldung oder per Anruf an die Suchleitung – nicht das Kind allein zurückbringen, wenn es sich wehrt: bei ihm bleiben und Hilfe holen.' },
      { text: 'Hausdienst: Aussentüren und Tore kontrollieren, Areal abschreiten, Zufahrt und Parkplatz prüfen, Kameras sichten falls vorhanden.', groupIds: ['gr-sicherheit'] },
      { text: 'Evakuationshelfer: Gebäude systematisch nach Suchplan absuchen – Keller, Technikräume, Verstecke – und jeden geprüften Raum melden.', groupIds: ['gr-evak'] },
      { text: 'Pädagogisches Team: Lieblingsorte und Rückzugsorte des Kindes nennen, Bezugsperson zur Suche schicken; das Kind reagiert eher auf eine bekannte Stimme.', groupIds: ['gr-paed'] },
      { text: 'Krisenstab: Suchleitung übernehmen, Protokoll führen, Polizei und Eltern über die Schulleitung informieren, Suchbereiche zuteilen.', groupIds: ['gr-krisenstab'] },
      { text: 'An einem anderen Standort: Beschreibung beachten, Umgebung im Blick behalten, erreichbar bleiben.' },
    ],
    allClearSteps: [
      'Das Kind ist gefunden: ruhig begleiten, kurz medizinisch prüfen lassen, keine Vorwürfe im Moment der Rückkehr.',
      'Suchende zurückrufen und zählen – niemand bleibt unbemerkt draussen.',
      'Übrige Kinder beruhigen und zum Tagesablauf zurückkehren; die Klasse des Kindes braucht ein kurzes Gespräch.',
      'Suchprotokoll abschliessen und der Schulleitung übergeben; Polizei über den Fund informieren, falls sie aufgeboten war.',
      'Aufsichtskonzept und individuelle Weglaufprävention innerhalb einer Woche überprüfen.',
    ],
    followUp: [
      'Schulleitung informiert die Eltern/Erziehungsberechtigten parallel zur Suche.',
      'Suchprotokoll führen: wer sucht wo, mit Zeitangabe – Doppelspurigkeit vermeiden.',
      'Nach dem Auffinden: kurz medizinisch prüfen, ruhig zurückbegleiten – keine Vorwürfe im Moment der Rückkehr.',
      'Vorfall auswerten: Aufsichtskonzept und individuelle Weglaufprävention anpassen.',
    ],
    checklist: ['Letzter Standort + Zeit erfasst', 'Suchalarm ausgelöst', 'Beschreibung verteilt', 'Gefahrenstellen abgesucht', 'Aufsicht geregelt', '117 nach 15 Min. oder sofort bei Gefahr', 'Eltern informiert', 'Suchprotokoll geführt'],
  },
  {
    id: 'sc-amok', icon: 'shield-alert', title: 'Amok / Bedrohungslage', category: 'Sicherheit', priority: 'hoch', silentDefault: true,
    defaultChannels: ['push', 'sms'], responsibleGroupIds: ['gr-alle'], contactIds: ['ec-117'],
    callGuidance: [
      'Zuerst in Sicherheit bringen, dann alarmieren: Der stille Alarm in der App warnt alle am Standort ohne Ton – keine Durchsage, keine Sirene.',
      'Polizei 117 anrufen, sobald es gefahrlos möglich ist – leise sprechen, nicht auflegen.',
      'Melden: Wer ruft an, Standort und Gebäude, was passiert (Waffe, Anzahl Täter), wo die Person zuletzt gesehen wurde, wie viele Personen betroffen sind.',
      'Ausdrücklich sagen: Sonderschule mit Kindern, die das Gebäude nicht selbständig verlassen können.',
      'Keine weiteren Anrufe, keine Nachrichten in Chats – die Leitungen und die Ruhe werden gebraucht.',
    ],
    instructions: [
      'Raus nur, wenn der Weg sicher frei ist – sonst: Raum verriegeln.',
      'Tür abschliessen oder verbarrikadieren (Pulte, Schränke), Licht aus, weg von Tür und Fenster, auf den Boden.',
      'Geräte stumm schalten. Kinder leise halten – bekannte Beruhigungsrituale nutzen, Körperkontakt zulassen.',
      'Niemanden auf den Gang lassen und niemandem öffnen, auch nicht auf Klopfen oder Rufen hin.',
      'Tür erst öffnen, wenn sich die Polizei eindeutig zu erkennen gibt.',
    ],
    responseSteps: [
      { text: 'Kein Anruf, keine Rückfrage, kein Ton: Der Alarm ist still, damit niemand auf sich aufmerksam macht. Gerät sofort stumm schalten.' },
      { text: 'Raum verriegeln: Tür abschliessen oder verbarrikadieren, Licht aus, weg von Tür und Fenster, auf den Boden.' },
      { text: 'Kinder leise halten – Beruhigungsrituale, Körperkontakt. Niemanden auf den Gang lassen, auch nicht auf Klopfen hin.' },
      { text: 'Nicht evakuieren, nicht zum Sammelplatz: Anders als beim Brand bleiben alle im Raum, bis die Polizei ihn öffnet.' },
      { text: 'Hausdienst: Wenn gefahrlos möglich, Eingänge verschliessen, Polizei an der vereinbarten Zufahrt erwarten, Gebäudepläne und Schlüssel bereithalten.', groupIds: ['gr-sicherheit'] },
      { text: 'Krisenstab: Sammelraum ausserhalb des Gebäudes festlegen, Elterninformation vorbereiten, Kontakt zur Einsatzleitung der Polizei halten – nicht ins Gebäude.', groupIds: ['gr-krisenstab'] },
      { text: 'Ersthelfer: nicht zum Ereignisort – Versorgung erst nach Freigabe durch die Polizei, Notfallrucksack im Sammelraum bereitstellen.', groupIds: ['gr-ersthelfer'] },
      { text: 'An einem anderen Standort: Türen schliessen, Aussenaktivitäten abbrechen, auf Weisungen des Krisenstabs warten.' },
      { text: 'Warten, bis die Polizei den Raum öffnet oder die Entwarnung über die App kommt – keine Entscheidung auf Zuruf.' },
    ],
    allClearSteps: [
      'Raum erst verlassen, wenn die Polizei sich eindeutig zu erkennen gibt oder der Krisenstab die Entwarnung bestätigt hat – nicht auf Zuruf, nicht auf einzelne Nachrichten.',
      'Anweisungen der Polizei befolgen: Hände sichtbar, keine hastigen Bewegungen, Kinder an der Hand.',
      'Zum bezeichneten Sammelraum; dort zählen, Vollständigkeit melden, Kinder nicht allein lassen.',
      'Eltern werden ausschliesslich durch die Schulleitung informiert – keine Fotos, keine Nachrichten in Chats.',
      'Care-Team und Notfallpsychologie werden aufgeboten – Unterstützung auch für Mitarbeitende annehmen.',
    ],
    followUp: [
      'Sammlung und Zählung erst nach Freigabe durch die Polizei.',
      'Eltern ausschliesslich über den offiziellen Kanal der Schulleitung informieren – keine Einzelauskünfte.',
      'Care-Team/Notfallpsychologie für Kinder und Mitarbeitende aufbieten.',
      'Medienanfragen ohne Ausnahme an die Schulleitung verweisen.',
    ],
    checklist: ['Raum verriegelt/verdunkelt', 'Stiller Alarm ausgelöst', '117 informiert', 'Kinder leise + betreut', 'Zählung nach Freigabe', 'Care-Team aufgeboten', 'Kommunikation gebündelt'],
  },
  {
    id: 'sc-bombe', icon: 'bomb', title: 'Bombendrohung', category: 'Sicherheit', priority: 'hoch', active: false, silentDefault: true,
    defaultChannels: ['push', 'sms'], responsibleGroupIds: ['gr-krisenstab', 'gr-sicherheit'], contactIds: ['ec-117'],
    instructions: [
      'Anruf ernst nehmen und in die Länge ziehen – nicht auflegen.',
      'Parallel notieren: exakter Wortlaut, Stimme, Sprache, Hintergrundgeräusche, angedrohter Ort/Zeitpunkt (Drohungsprotokoll liegt beim Telefon).',
      'Nach dem Anruf: Polizei 117 anrufen und Krisenstab per App aufbieten.',
      'Keine eigenmächtige Evakuierung und keine Durchsagen – Entscheid trifft der Krisenstab mit der Polizei.',
      'Verdächtige Gegenstände nicht berühren, nicht bewegen, Umgebung freihalten.',
      'Mobilfunkgeräte in der Nähe verdächtiger Gegenstände nicht benutzen.',
    ],
    followUp: [
      'Entscheid Evakuierung/Durchsuchung gemeinsam mit der Polizei umsetzen (dann Ablauf «Evakuierung Schulhaus»).',
      'Eltern nach Lagebeurteilung offiziell durch die Schulleitung informieren.',
      'Drohungsprotokoll und Ereignisjournal der Polizei übergeben.',
    ],
    checklist: ['Drohungsprotokoll ausgefüllt', '117 informiert', 'Krisenstab quittiert', 'Keine eigenmächtige Räumung', 'Entscheid dokumentiert', 'Eltern informiert'],
  },
  {
    id: 'sc-transport', icon: 'bus', title: 'Unfall Schülertransport', category: 'Schüler:innen', priority: 'hoch', active: false, silentDefault: false,
    defaultChannels: ['push', 'sms', 'voice'], responsibleGroupIds: ['gr-krisenstab', 'gr-ersthelfer'], contactIds: ['ec-144', 'ec-117'],
    instructions: [
      'Warnblinker ein, Pannendreieck stellen, Warnweste an – Unfallstelle sichern.',
      'Kinder im Fahrzeug lassen, wenn dort sicher; sonst hinter die Leitplanke, nie auf die Fahrbahn.',
      'Verletzte versorgen: 144 anrufen (Standort, Anzahl Kinder, Zustand).',
      'Bei Blechschaden oder blockierter Strasse zusätzlich 117.',
      'Schule per App alarmieren: Standort, welche Kinder betroffen, was wird gebraucht.',
      'Alle Kinder anhand der Transportliste zählen – niemand verlässt die Gruppe.',
    ],
    followUp: [
      'Schulleitung informiert die Eltern aller betroffenen Kinder persönlich.',
      'Ersatztransport und Betreuung vor Ort organisieren (Krisenstab).',
      'Spitalbegleitung sicherstellen, Übergabe an Eltern dokumentieren.',
      'Transportunternehmen und Versicherung melden; Kinder in den Folgetagen auf Fahrangst achten.',
    ],
    checklist: ['Unfallstelle gesichert', '144/117 alarmiert', 'Schule informiert', 'Transportliste abgeglichen', 'Eltern informiert', 'Ersatztransport organisiert', 'Nachbetreuung geplant'],
  },
  {
    id: 'sc-medikament', icon: 'pill', title: 'Medikamenten-Zwischenfall', category: 'Gesundheit', priority: 'hoch', active: false, silentDefault: false,
    defaultChannels: ['push', 'voice'], responsibleGroupIds: ['gr-ersthelfer', 'gr-krisenstab'], contactIds: ['ec-145', 'ec-144'],
    instructions: [
      'Was ist passiert? Falsches Medikament, falsche Dosis, falsches Kind, vergessene Gabe oder fremde Einnahme – sofort melden, nicht vertuschen.',
      'Medikamentenpackung/Blister sicherstellen – nichts wegwerfen.',
      'Tox Info Suisse 145 anrufen: Präparat, Dosis, Zeitpunkt, Gewicht des Kindes bereithalten.',
      'Anweisungen von Tox Info exakt befolgen – kein Erbrechen auslösen, nichts einflössen.',
      'Kind lückenlos beobachten (Bewusstsein, Atmung, Haut) – bei Symptomen sofort 144.',
      'Schulsanität per App beiziehen.',
    ],
    followUp: [
      'Eltern und behandelnde Ärztin/Arzt am selben Tag informieren.',
      'Zwischenfall im Medikamentenjournal dokumentieren (wer, was, wann, Massnahmen).',
      'Abgabeprozess prüfen: Vier-Augen-Prinzip, Beschriftung, Aufbewahrung – Massnahmen festlegen.',
    ],
    checklist: ['145 kontaktiert', 'Packung sichergestellt', 'Kind unter Beobachtung', '144 beurteilt', 'Eltern + Arzt informiert', 'Journal dokumentiert', 'Prozess angepasst'],
  },
  {
    id: 'sc-psych', icon: 'life-buoy', title: 'Akute psychische Krise / Suizidalität', category: 'Schüler:innen', priority: 'hoch', active: false, silentDefault: true,
    defaultChannels: ['push'], responsibleGroupIds: ['gr-krisenstab', 'gr-paed'], contactIds: ['ec-144', 'ec-143', 'ec-147'],
    instructions: [
      'Bei der Person bleiben – sie ab jetzt keine Minute allein lassen.',
      'Äusserungen ernst nehmen, ruhig zuhören, nichts versprechen («Das wird schon») – direkte Fragen sind erlaubt und entlasten.',
      'Gefährliche Gegenstände und Medikamente unauffällig ausser Reichweite bringen.',
      'Still per App die Schulleitung/Fachperson beiziehen (Schulpsychologie/KJPP) – nicht selbst therapieren.',
      'Bei akuter Selbstgefährdung: 144 anrufen und die Person begleitet übergeben.',
    ],
    followUp: [
      'Eltern/Erziehungsberechtigte durch Fachperson oder Schulleitung einbeziehen.',
      'Übergabe an KJPP/Notfallpsychiatrie dokumentieren (wer, wann, an wen).',
      'Wiedereinstieg planen: Absprachen, Betreuungsplan, feste Ansprechperson, regelmässiges Monitoring.',
      'Klassenumfeld sensibilisieren, ohne Details preiszugeben.',
    ],
    checklist: ['Person begleitet (nie allein)', 'Gegenstände gesichert', 'Fachperson beigezogen', '144 beurteilt', 'Übergabe dokumentiert', 'Eltern einbezogen', 'Wiedereinstieg geplant'],
  },
  {
    id: 'sc-kindesschutz', icon: 'shield-alert', title: 'Kindesschutz – Verdacht auf Gefährdung', category: 'Schüler:innen', priority: 'mittel', active: false, silentDefault: true,
    defaultChannels: ['push'], responsibleGroupIds: ['gr-krisenstab'], contactIds: ['ec-147'],
    instructions: [
      'Dem Kind ruhig zuhören, ernst nehmen – nichts versprechen, was nicht gehalten werden kann («Ich behalte das für mich» geht nicht).',
      'Keine Suggestivfragen, keine eigene Befragung, keine Konfrontation der mutmasslich beteiligten Personen.',
      'Beobachtungen sofort sachlich notieren: Datum, Situation, wörtliche Aussagen, sichtbare Anzeichen.',
      'Kindesschutzgruppe/Schulleitung still und vertraulich informieren – nicht im Lehrerzimmer besprechen.',
      'Bei akuter Gefahr für das Kind: Schulleitung entscheidet sofort über Polizei/KESB.',
    ],
    followUp: [
      'Kindesschutzgruppe beurteilt das Vorgehen: Fachstelle beiziehen, Gefährdungsmeldung an die KESB prüfen.',
      'Schutz und Normalität für das Kind im Schulalltag sicherstellen.',
      'Dokumentation vertraulich und revisionssicher ablegen – Zugriff nur für die Kindesschutzgruppe.',
    ],
    checklist: ['Zugehört, nichts versprochen', 'Beobachtungen dokumentiert', 'Kindesschutzgruppe informiert', 'Vertraulichkeit gewahrt', 'Vorgehen festgelegt', 'Schutz im Alltag geregelt'],
  },
  {
    id: 'sc-strom', icon: 'zap-off', title: 'Stromausfall', category: 'Gebäude & Technik', priority: 'tief', active: false, silentDefault: false,
    defaultChannels: ['push', 'sms'], responsibleGroupIds: ['gr-sicherheit'], contactIds: [],
    instructions: [
      'Kinder beruhigen – Dunkelheit kann Ängste auslösen; Taschenlampen statt Kerzen.',
      'Hausdienst per App alarmieren – er prüft Sicherungen, Notbeleuchtung und Ursache.',
      'Aufzüge sofort kontrollieren: eingeschlossene Personen? Beruhigen, Hausdienst befreit oder ruft den Aufzugsdienst.',
      'Elektrische Hilfsmittel prüfen: Lifter, Pflegebetten, Kommunikationsgeräte – Akkustand sichern, Prioritäten setzen.',
      'Bei grossflächigem Ausfall: Energieversorger kontaktieren, Dauer erfragen.',
    ],
    followUp: [
      'Bei längerem Ausfall: Unterricht anpassen, warme Räume bündeln, Schulleitung entscheidet über vorzeitige Abholung.',
      'Kühlketten prüfen (Küche, Medikamente im Kühlschrank) und dokumentieren.',
      'Nach Wiederkehr: Anlagen kontrolliert hochfahren, Uhren/Anlagen zurückstellen.',
    ],
    checklist: ['Hausdienst alarmiert', 'Aufzüge geprüft', 'Akku-Hilfsmittel gesichert', 'Versorger kontaktiert', 'Kühlketten geprüft', 'Eltern informiert (bei Bedarf)'],
  },
  {
    id: 'sc-wasser', icon: 'droplets', title: 'Wasserschaden', category: 'Gebäude & Technik', priority: 'tief', active: false, silentDefault: false,
    defaultChannels: ['push'], responsibleGroupIds: ['gr-sicherheit'], contactIds: ['ec-118'],
    instructions: [
      'Personen aus dem betroffenen Bereich – Rutsch- und Stromschlaggefahr.',
      'Strom im betroffenen Bereich abschalten (Sicherung), bevor jemand ins Wasser tritt.',
      'Wasserzufuhr stoppen: Absperrhahn im Raum oder Haupthahn (Technikraum UG).',
      'Hausdienst per App alarmieren, Bereich absperren.',
      'Wertvolles und Wichtiges hochstellen oder wegräumen (Akten, Geräte, Therapiehilfsmittel).',
      'Bei grossem Wassereinbruch: Feuerwehr 118 (Wasserwehr) anrufen.',
    ],
    followUp: [
      'Unterricht in Ersatzräume verlegen, Raumbelegung anpassen.',
      'Trocknungsfirma und Gebäudeversicherung aufbieten, Schaden fotografieren.',
      'Ursache beheben lassen und Kontrolle nach einer Woche einplanen (Schimmel).',
    ],
    checklist: ['Bereich geräumt', 'Strom getrennt', 'Wasser gestoppt', 'Hausdienst vor Ort', 'Schaden dokumentiert', 'Versicherung gemeldet', 'Räume verlegt'],
  },
  {
    id: 'sc-unwetter', icon: 'cloud-lightning', title: 'Unwetter / Sturm', category: 'Naturereignis', priority: 'mittel', active: false, silentDefault: false,
    defaultChannels: ['push', 'sms'], responsibleGroupIds: ['gr-sicherheit', 'gr-alle'], contactIds: [],
    instructions: [
      'Alle nach drinnen – Pausen, Sport und Ausflüge im Freien sofort abbrechen.',
      'Warnung per App an den Standort senden, damit alle Gruppen reagieren.',
      'Fenster und Türen schliessen, Storen einfahren (Windbruch), von grossen Fensterflächen fernhalten.',
      'Lose Gegenstände im Aussenbereich sichern: Spielgeräte, Sonnenschirme, Abfalleimer.',
      'Wetterlage verfolgen (MeteoSchweiz-App) – Entwarnung abwarten.',
      'Schülertransporte prüfen: Abfahrten verschieben, Fahrer und Eltern informieren.',
    ],
    followUp: [
      'Areal erst nach Entwarnung kontrollieren: Äste, Dachteile, Leitungen – Gefahrenstellen absperren.',
      'Heimweg der Kinder koordinieren (Transport, Begleitung, Abholung).',
      'Schäden dokumentieren und der Versicherung melden.',
    ],
    checklist: ['Alle im Gebäude', 'Warnung versendet', 'Gebäude gesichert', 'Aussenbereich gesichert', 'Transporte koordiniert', 'Areal nach Entwarnung geprüft'],
  },
  {
    id: 'sc-pandemie', icon: 'biohazard', title: 'Pandemie / Infektionsfall', category: 'Gesundheit', priority: 'mittel', active: false, silentDefault: false,
    defaultChannels: ['push', 'email'], responsibleGroupIds: ['gr-krisenstab'], contactIds: [],
    instructions: [
      'Erkrankte Person freundlich separieren (Sanitätszimmer) und betreuen – nicht allein lassen.',
      'Krisenstab per App informieren – er koordiniert Massnahmen und Kommunikation.',
      'Hygiene sofort verschärfen: Hände waschen, Flächen desinfizieren, regelmässig lüften.',
      'Kontaktpersonen ermitteln – besonders vulnerable Kinder (Grunderkrankungen) zuerst schützen.',
      'Vorgaben von BAG und Kantonsarzt einholen und exakt umsetzen.',
      'Abholung durch die Eltern organisieren.',
    ],
    followUp: [
      'Eltern des Standorts sachlich über Lage und Massnahmen informieren (ohne Namen).',
      'Absenzen täglich monitoren – bei Häufung Kantonsarzt kontaktieren.',
      'Fernbetreuungs-/Unterrichtskonzept bereithalten und bei Bedarf aktivieren.',
    ],
    checklist: ['Person separiert + betreut', 'Krisenstab informiert', 'Hygienekonzept aktiv', 'Kontakte ermittelt', 'Behördenvorgaben umgesetzt', 'Eltern informiert', 'Absenzenmonitoring läuft'],
  },
]

export const SEED_LOCATIONS: Location[] = [
  {
    id: 'loc-baar', name: 'Hauptsitz Baar', address: 'SONNENBERG Kompetenzzentrum, 6340 Baar',
    geofence: { lat: 47.1954, lng: 8.5289, radiusM: 400 },
    operatingHours: { days: 'Mo–So (inkl. Wohngruppen)', open: '00:00', close: '24:00' },
  },
  {
    id: 'loc-menzingen', name: 'Standort Menzingen', address: 'Schulstandort, 6313 Menzingen',
    geofence: { lat: 47.1773, lng: 8.5921, radiusM: 300 },
    operatingHours: { days: 'Mo–Fr', open: '07:00', close: '18:00' },
  },
  {
    id: 'loc-kloten', name: 'Standort Kloten', address: 'Schulstandort, 8302 Kloten',
    geofence: { lat: 47.4515, lng: 8.585, radiusM: 300 },
    operatingHours: { days: 'Mo–Fr', open: '07:00', close: '18:00' },
  },
]

export const SEED_GROUPS: Group[] = [
  { id: 'gr-krisenstab', name: 'Krisenstab', description: 'Schulleitung und Bereichsleitungen – Führungsorgan für ausserordentliche Lagen', isCrisisTeam: true },
  { id: 'gr-ersthelfer', name: 'Schulsanität / Ersthelfer', description: 'Ausgebildete Ersthelfer mit BLS-AED und Medikamentenschulung', isCrisisTeam: true },
  { id: 'gr-evak', name: 'Evakuationshelfer', description: 'Gebäude- und Etagenverantwortliche, Umsetzung individueller Evakuationspläne', isCrisisTeam: true },
  { id: 'gr-paed', name: 'Deeskalationsteam', description: 'Sozialpädagogisch geschulte Mitarbeitende für herausfordernde Situationen', isCrisisTeam: true },
  { id: 'gr-it', name: 'IT-Support', description: 'Incident Response und Systemwiederherstellung', isCrisisTeam: false },
  { id: 'gr-sicherheit', name: 'Hausdienst & Empfang', description: 'Technischer Dienst, Empfang und Arealsicherheit', isCrisisTeam: false },
  { id: 'gr-alle', name: 'Alle Mitarbeitenden', description: 'Gesamtes Personal aller Standorte', isCrisisTeam: false },
]

export const SEED_USERS: User[] = [
  { id: 'u-admin', firstName: 'Stefan', lastName: 'Gross', email: 'stefan.gross@sonnenberg-baar.ch', phone: '+41 79 100 10 01', role: 'admin', groupIds: ['gr-krisenstab', 'gr-alle'], locationId: 'loc-baar', language: 'de', passwordSalt: '8abffbd4978a8235', passwordHash: '2aef5f18d380585a2f435fbcf32d667d5e6c3daed5c75228afe384cf3af939be' },
  { id: 'u-mueller', firstName: 'Anna', lastName: 'Müller', email: 'anna.mueller@sonnenberg-baar.ch', phone: '+41 79 100 10 02', role: 'krisenstab', groupIds: ['gr-krisenstab', 'gr-alle'], locationId: 'loc-baar', language: 'de', passwordSalt: '08ca19311fbba160', passwordHash: '1f249d4fa8084561a881d109953a4148b0631f1952c1ae0a7bd17e72318eede6' },
  { id: 'u-rossi', firstName: 'Marco', lastName: 'Rossi', email: 'marco.rossi@sonnenberg-baar.ch', phone: '+41 79 100 10 03', role: 'krisenstab', groupIds: ['gr-krisenstab', 'gr-paed', 'gr-alle'], locationId: 'loc-menzingen', language: 'it', passwordSalt: '63935256684aec74', passwordHash: 'da7d1cc5f05082f5ee540b9b63587b4a76234464ef88948271e0cacd146ef09d' },
  { id: 'u-weber', firstName: 'Lea', lastName: 'Weber', email: 'lea.weber@sonnenberg-baar.ch', phone: '+41 79 100 10 04', role: 'mitarbeiter', groupIds: ['gr-ersthelfer', 'gr-alle'], locationId: 'loc-baar', language: 'de', passwordSalt: 'e3cb7f472098396c', passwordHash: 'a33c1a168115f31884c38eb2dfc728b05deca3b301c084d5f25efe12296f2624' },
  { id: 'u-favre', firstName: 'Julien', lastName: 'Favre', email: 'julien.favre@sonnenberg-baar.ch', phone: '+41 79 100 10 05', role: 'mitarbeiter', groupIds: ['gr-paed', 'gr-evak', 'gr-alle'], locationId: 'loc-menzingen', language: 'fr', passwordSalt: '6a1f035f943f9969', passwordHash: '16aee1329273914e79457809669bef28557feb072f67a02995ca0dc8f26865a1' },
  { id: 'u-keller', firstName: 'Sandra', lastName: 'Keller', email: 'sandra.keller@sonnenberg-baar.ch', phone: '+41 79 100 10 06', role: 'mitarbeiter', groupIds: ['gr-it', 'gr-alle'], locationId: 'loc-baar', language: 'de', passwordSalt: '916b5b0c6272a02f', passwordHash: '241b34a7a7f0ef73cc09437c50c53fa427c223454fe30c78e653d36498cf2c25', partTimeNote: '60 %, Mo–Mi' },
  { id: 'u-huber', firstName: 'Thomas', lastName: 'Huber', email: 'thomas.huber@sonnenberg-baar.ch', phone: '+41 79 100 10 07', role: 'mitarbeiter', groupIds: ['gr-sicherheit', 'gr-alle'], locationId: 'loc-baar', language: 'de', passwordSalt: '571aa5c023c79f4b', passwordHash: 'f16d42e7e1ebb76b0493e452c32cf567a8deaab1936751ea3f6f1b442d8f5cfc' },
  { id: 'u-brunner', firstName: 'Nicole', lastName: 'Brunner', email: 'nicole.brunner@sonnenberg-baar.ch', phone: '+41 79 100 10 08', role: 'mitarbeiter', groupIds: ['gr-alle'], locationId: 'loc-kloten', language: 'de', passwordSalt: 'c5eab44e91ba1412', passwordHash: '59c866dd4db245f31ed66d843bafa5675d2a6baf2439c90c0a786421f8abcfb5', absence: { from: '2026-08-10', to: '2026-08-24' } },
  { id: 'u-meier', firstName: 'David', lastName: 'Meier', email: 'david.meier@sonnenberg-baar.ch', phone: '+41 79 100 10 09', role: 'mitarbeiter', groupIds: ['gr-evak', 'gr-alle'], locationId: 'loc-kloten', language: 'en', passwordSalt: 'b0b416586e60b270', passwordHash: '5acb228842607b28bcbe39ffe523fae0b9685222ef39e3b24321747cd18bcd58' },
  { id: 'u-schmid', firstName: 'Petra', lastName: 'Schmid', email: 'petra.schmid@sonnenberg-baar.ch', phone: '+41 79 100 10 10', role: 'mitarbeiter', groupIds: ['gr-ersthelfer', 'gr-paed', 'gr-alle'], locationId: 'loc-baar', language: 'de', passwordSalt: 'eb6195c97f3f50c0', passwordHash: 'b2d27876d188ceee4574c5bae3360554ee4982fd3d966c28d743db31b5a49f75' },
]

export const SEED_PLANS: AlarmPlan[] = [
  {
    id: 'pl-brand-baar', name: 'Brandalarm Hauptsitz Baar', scenarioId: 'sc-brand',
    locationIds: ['loc-baar'], groupIds: ['gr-alle'],
    channels: ['push', 'sms', 'tts'], requireAck: false, respectOperatingHours: false,
    escalation: [
      { afterMinutes: 3, channels: ['voice'], groupIds: ['gr-evak'], notifyEmergencyServices: false },
      { afterMinutes: 10, channels: ['voice', 'sms'], groupIds: ['gr-krisenstab'], notifyEmergencyServices: true },
    ],
  },
  {
    id: 'pl-krisenstab', name: 'Aufgebot Krisenstab (mit Quittierung)', scenarioId: 'sc-krise',
    locationIds: ['loc-baar', 'loc-menzingen', 'loc-kloten'], groupIds: ['gr-krisenstab'],
    channels: ['push', 'sms', 'voice', 'conference'], requireAck: true, respectOperatingHours: false,
    escalation: [
      { afterMinutes: 5, channels: ['voice'], groupIds: ['gr-krisenstab'], notifyEmergencyServices: false },
    ],
  },
  {
    id: 'pl-vermisst', name: 'Vermisste:r Schüler:in – Suchaktion', scenarioId: 'sc-vermisst',
    locationIds: [], groupIds: ['gr-alle'],
    channels: ['push', 'sms'], requireAck: true, respectOperatingHours: false,
    escalation: [
      { afterMinutes: 10, channels: ['voice'], groupIds: ['gr-krisenstab'], notifyEmergencyServices: false },
      { afterMinutes: 20, channels: ['voice', 'sms'], groupIds: ['gr-krisenstab'], notifyEmergencyServices: true },
    ],
  },
  {
    id: 'pl-medizin', name: 'Medizinischer Notfall (Schulsanität)', scenarioId: 'sc-medizin',
    locationIds: [], groupIds: ['gr-ersthelfer'],
    channels: ['push', 'voice'], requireAck: true, respectOperatingHours: true,
    escalation: [
      { afterMinutes: 2, channels: ['voice', 'sms'], groupIds: ['gr-sicherheit'], notifyEmergencyServices: true },
    ],
  },
  {
    id: 'pl-eskalation', name: 'Deeskalationsteam (stiller Alarm)', scenarioId: 'sc-gewalt',
    locationIds: [], groupIds: ['gr-paed'],
    channels: ['push'], requireAck: true, respectOperatingHours: true,
    escalation: [
      { afterMinutes: 3, channels: ['push', 'voice'], groupIds: ['gr-sicherheit', 'gr-krisenstab'], notifyEmergencyServices: false },
    ],
  },
  {
    id: 'pl-it', name: 'IT-Incident Response', scenarioId: 'sc-it',
    locationIds: [], groupIds: ['gr-it'],
    channels: ['push', 'email', 'teams'], requireAck: true, respectOperatingHours: false,
    escalation: [
      { afterMinutes: 15, channels: ['voice'], groupIds: ['gr-krisenstab'], notifyEmergencyServices: false },
    ],
  },
]

export const SEED_BUTTONS: AlarmButton[] = [
  {
    id: 'btn-1', name: 'Empfang Hauptsitz Baar', type: 'lorawan', serial: 'LW-8842-A1',
    locationId: 'loc-baar', assignedUserId: 'u-huber', batteryPct: 92,
    lastSeen: Date.now() - 5 * 60_000,
    messageTemplate: 'Stiller Alarm Empfang Baar – Bedrohungslage möglich. Nicht zurückrufen.',
    targetGroupIds: ['gr-sicherheit', 'gr-krisenstab'], escalateToEmergencyServicesAfterMin: 5,
  },
  {
    id: 'btn-2', name: 'Therapiebad Baar', type: 'lorawan', serial: 'LW-8901-C7',
    locationId: 'loc-baar', batteryPct: 100,
    lastSeen: Date.now() - 2 * 60_000,
    messageTemplate: 'Alarmknopf Therapiebad ausgelöst – sofort Schulsanität ins Bad!',
    targetGroupIds: ['gr-ersthelfer', 'gr-sicherheit'], escalateToEmergencyServicesAfterMin: 3,
  },
  {
    id: 'btn-3', name: 'Schülertransport Bus 1 (Kloten)', type: 'gsm', serial: 'GSM-1207-B4',
    assignedUserId: 'u-meier', batteryPct: 67,
    lastSeen: Date.now() - 42 * 60_000, gps: { lat: 47.4489, lng: 8.5761 },
    messageTemplate: 'Notfallknopf Schülertransport Bus 1 ausgelöst – GPS-Position beachten.',
    targetGroupIds: ['gr-krisenstab', 'gr-ersthelfer'], escalateToEmergencyServicesAfterMin: 5,
  },
  {
    id: 'btn-4', name: 'Wohngruppe Menzingen', type: 'lorawan', serial: 'LW-9014-D2',
    locationId: 'loc-menzingen', assignedUserId: 'u-favre', batteryPct: 88,
    lastSeen: Date.now() - 8 * 60_000,
    messageTemplate: 'Alarmknopf Wohngruppe Menzingen – Unterstützung durch Deeskalationsteam angefordert.',
    targetGroupIds: ['gr-paed', 'gr-krisenstab'], escalateToEmergencyServicesAfterMin: 10,
  },
]

export const SEED_CONTACTS: EmergencyContact[] = [
  { id: 'ec-117', name: 'Polizei', number: '117', description: 'Polizeinotruf Schweiz' },
  { id: 'ec-118', name: 'Feuerwehr', number: '118', description: 'Feuerwehrnotruf Schweiz' },
  { id: 'ec-144', name: 'Sanität', number: '144', description: 'Sanitätsnotruf Schweiz' },
  { id: 'ec-112', name: 'Europäischer Notruf', number: '112', description: 'Internationale Notrufnummer' },
  { id: 'ec-145', name: 'Tox Info Suisse', number: '145', description: 'Vergiftungs- und Medikamentennotfälle' },
  { id: 'ec-1414', name: 'Rega', number: '1414', description: 'Rettungsflugwacht' },
  { id: 'ec-143', name: 'Dargebotene Hand', number: '143', description: 'Telefonseelsorge für Erwachsene' },
  { id: 'ec-147', name: 'Pro Juventute', number: '147', description: 'Beratung für Kinder und Jugendliche' },
]

export const SEED_INTEGRATIONS: IntegrationSettings = {
  smsGateway: { enabled: true, provider: 'ecall', senderId: 'SONNENBERG', username: 'sonnenberg-demo', password: 'demo-geheim', httpUrl: '', sentCount: 128 },
  telephony: { enabled: true, tenantId: 'sonnenberg-baar.onmicrosoft.com', clientId: '00000000-demo-4000-a000-000000000000', clientSecret: 'demo-geheim', organizerEmail: 'krisenstab@sonnenberg-baar.ch' },
  teams: { enabled: true, tenant: 'sonnenberg-baar.onmicrosoft.com', webhookUrl: 'https://sonnenbergbaar.webhook.office.com/webhookb2/demo' },
  lorawan: { enabled: true, provider: 'ttn', token: 'lw_demo0000000000000000000000000000000000000000000000' },
  sso: { enabled: false, provider: 'Microsoft Entra ID / SAML 2.0', entityId: '' },
  hrSync: { enabled: false, system: 'Abacus HR' },
  hotline: { enabled: true, number: '+41 41 767 49 48' },
  multiLanguage: true,
  geofencing: true,
  webhooks: [
    { id: 'wh-1', name: 'Brandmeldeanlage Hauptsitz Baar', url: 'https://alarmserver.example/api/inbound/bma-baar', direction: 'inbound', scenarioId: 'sc-brand', active: true },
    { id: 'wh-2', name: 'Leitstellen-Export', url: 'https://leitstelle.example/api/events', direction: 'outbound', active: true },
  ],
  accessCodes: [
    { code: 'BA-4X9K2M', locationId: 'loc-baar', role: 'mitarbeiter', createdAt: Date.now() - 86400_000 * 12, used: 34 },
    { code: 'ME-7Q1R8T', locationId: 'loc-menzingen', role: 'mitarbeiter', createdAt: Date.now() - 86400_000 * 30, used: 21 },
    { code: 'KL-2P5W9V', locationId: 'loc-kloten', role: 'mitarbeiter', createdAt: Date.now() - 86400_000 * 30, used: 17 },
  ],
}

/** Passwort aller Demo-Benutzer – wird auf der Anmeldemaske im Demo-Modus angezeigt */
export const DEMO_PASSWORD = 'sobe2026'

/** Erstpasswort des Live-Administrators; muss bei der ersten Anmeldung geändert werden */
export const LIVE_INITIAL_PASSWORD = 'SOBE-Start2026!'

export function createInitialState(): AppState {
  return {
    mode: 'demo',
    session: null,
    scenarioContentVersion: SCENARIO_CONTENT_VERSION,
    currentUserId: 'u-admin',
    users: SEED_USERS,
    groups: SEED_GROUPS,
    locations: SEED_LOCATIONS,
    scenarios: SEED_SCENARIOS,
    plans: SEED_PLANS,
    alarms: [],
    buttons: SEED_BUTTONS,
    loneWorkSessions: [],
    integrations: SEED_INTEGRATIONS,
    contacts: SEED_CONTACTS,
    audit: [
      { id: 'a-1', ts: Date.now() - 3600_000, type: 'system', message: 'System initialisiert – Alarmserver für SONNENBERG Kompetenzzentrum betriebsbereit (Cloud-Hosting Schweiz).' },
    ],
  }
}

/**
 * Live-Modus: echter Datenbestand ohne Mock-Daten.
 * Behalten wird nur reale Grundkonfiguration (Szenarien, Standorte, Gruppenstruktur,
 * Notrufnummern, Alarmplan-Vorlagen) plus ein Admin-Konto. Keine Beispiel-Benutzer,
 * -Alarme, -Alarmknöpfe, -Webhooks oder -Zugangscodes; alle Integrationen deaktiviert.
 */
export function createLiveInitialState(): AppState {
  return {
    mode: 'live',
    session: null,
    scenarioContentVersion: SCENARIO_CONTENT_VERSION,
    currentUserId: 'u-admin',
    users: [
      {
        id: 'u-admin', firstName: 'Stefan', lastName: 'Gross', email: 'stefan.gross@sonnenberg-baar.ch',
        phone: '', role: 'admin', groupIds: ['gr-krisenstab', 'gr-alle'], locationId: 'loc-baar', language: 'de',
        passwordSalt: 'bd631b09890e1d5d', passwordHash: '04b1c430ab36995b316131aef36a319b105b37a521680291dc490c387ff135c4', mustChangePassword: true,
      },
    ],
    groups: SEED_GROUPS,
    locations: SEED_LOCATIONS,
    scenarios: SEED_SCENARIOS,
    plans: SEED_PLANS,
    alarms: [],
    buttons: [],
    loneWorkSessions: [],
    integrations: {
      smsGateway: { enabled: false, provider: 'ecall', senderId: 'SONNENBERG', username: '', password: '', httpUrl: '', sentCount: 0 },
      telephony: { enabled: false, tenantId: '', clientId: '', clientSecret: '', organizerEmail: '' },
      teams: { enabled: false, tenant: '', webhookUrl: '' },
      lorawan: { enabled: false, provider: 'ttn', token: '' },
      sso: { enabled: false, provider: 'Microsoft Entra ID / SAML 2.0', entityId: '' },
      hrSync: { enabled: false, system: '' },
      hotline: { enabled: false, number: '' },
      multiLanguage: true,
      geofencing: false,
      webhooks: [],
      accessCodes: [],
    },
    contacts: SEED_CONTACTS,
    audit: [
      { id: 'a-live-1', ts: Date.now(), type: 'system', message: 'Live-Modus initialisiert – Datenbestand ohne Demo-Daten. Versand-Gateways unter Integrationen anbinden.' },
    ],
  }
}
